####################################################################
# Automatically-generated file. Do not edit!                       #
####################################################################

set(SDK_PATH "C:/Users/vinhv/.silabs/slt/installs/conan/p/simpl35774a752829c/p")
set(COPIED_SDK_PATH "simplicity_sdk_2025.12.3")
set(PKG_PATH "C:/Users/vinhv/.silabs/slt/installs")

add_library(slc OBJECT
    "${SDK_PATH}/bluetooth_common/src/sli_bgcommon_debug_efr32.c"
    "${SDK_PATH}/bluetooth_le_controller/src/sl_btctrl_init.c"
    "${SDK_PATH}/bluetooth_le_controller/src/sl_btctrl_init_tasklets.c"
    "${SDK_PATH}/bluetooth_le_host/src/sl_bt_rtos_adaptation.c"
    "${SDK_PATH}/bluetooth_le_host/src/sl_bt_stack_init.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_accept_list_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_advertiser_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_connection_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_dynamic_gattdb_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_external_bondingdb_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_hci_event_table.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_host_adaptation.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_l2cap_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_pawr_advertiser_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_periodic_advertiser_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_sync_config.c"
    "${SDK_PATH}/cmsis/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/cmsis_common/platform/common/src/sl_cmsis_os2_common.c"
    "${SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32MG21/Source/startup_efr32mg21.c"
    "${SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32MG21/Source/system_efr32mg21.c"
    "${SDK_PATH}/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/freertos/kernel/croutine.c"
    "${SDK_PATH}/freertos/kernel/event_groups.c"
    "${SDK_PATH}/freertos/kernel/list.c"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/mpu_wrappers_v2_asm.c"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c"
    "${SDK_PATH}/freertos/kernel/portable/MemMang/heap_3.c"
    "${SDK_PATH}/freertos/kernel/portable/SiliconLabs/cortexm/tick_power_manager.c"
    "${SDK_PATH}/freertos/kernel/queue.c"
    "${SDK_PATH}/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/freertos/kernel/tasks.c"
    "${SDK_PATH}/freertos/kernel/timers.c"
    "${SDK_PATH}/platform_common/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform_common/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform_common/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform_core/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform_core/platform/driver/button/src/sl_button.c"
    "${SDK_PATH}/platform_core/platform/driver/button/src/sl_simple_button.c"
    "${SDK_PATH}/platform_core/platform/driver/gpio/src/sl_gpio.c"
    "${SDK_PATH}/platform_core/platform/driver/leddrv/src/sl_led.c"
    "${SDK_PATH}/platform_core/platform/driver/leddrv/src/sl_simple_led.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_cache.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_object.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_page.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_utils.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_burtc.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_cmu.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_emu.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_gpio.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_msc.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_prs.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_rtcc.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_system.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_timer.c"
    "${SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_gpio.c"
    "${SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_syscfg.c"
    "${SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_system.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_init.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_init_hal_s2.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg21.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/dma/sl_device_dma_s2.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_clock.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_dma.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_gpio.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_peripheral.c"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/profiler/src/sli_memory_profiler_stubs.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_pool_common.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "${SDK_PATH}/platform_core/platform/service/mpu/src/sl_mpu_s2.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/common/sl_power_manager_common.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/common/sl_power_manager_em4.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager_debug.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/rtos/main_retarget.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_init.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_init_memory.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_kernel.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "${SDK_PATH}/platform_core/platform/service/udelay/src/sl_udelay.c"
    "${SDK_PATH}/platform_core/platform/service/udelay/src/sl_udelay_armv6m_gcc.S"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions/sl_rail_util_pa_conversions.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions/sl_rail_util_pa_tables.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pti/sl_rail_util_pti.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_rf_path/sl_rail_util_rf_path.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src/sli_protocol_crypto_radioaes.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src/sli_radioaes_management.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_aead.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_builtin_keys.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_cipher.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_derivation.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_management.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_mac.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_signature.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_aead.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_cipher.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_mac.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_key_derivation.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_aead.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_cipher.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_hash.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_mac.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_key_derivation.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sli_crypto/src/sl_crypto_s2.c"
    "${SDK_PATH}/security_mbedtls_source/library/cipher.c"
    "${SDK_PATH}/security_mbedtls_source/library/cipher_wrap.c"
    "${SDK_PATH}/security_mbedtls_source/library/constant_time.c"
    "${SDK_PATH}/security_mbedtls_source/library/platform.c"
    "${SDK_PATH}/security_mbedtls_source/library/platform_util.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_aead.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_cipher.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_client.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_driver_wrappers_no_static.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_ecp.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_ffdh.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_hash.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_mac.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_pake.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_rsa.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_se.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_slot_management.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_storage.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_util.c"
    "${SDK_PATH}/security_mbedtls_source/library/threading.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/sli_psec_osal/src/sli_psec_osal_cmsis_rtos2.c"
    "../app.c"
    "../app_freertos.c"
    "../autogen/gatt_db.c"
    "../autogen/sl_bluetooth.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_simple_button_instances.c"
    "../autogen/sl_simple_led_instances.c"
    "../main.c"
    "../sl_gatt_service_device_information_override.c"
)

target_include_directories(slc PUBLIC
   "../autogen"
   "../config"
   "../config/btconf"
   "../."
    "${SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32MG21/Include"
    "${SDK_PATH}/platform_common_apps/app/common/util/app_assert"
    "${SDK_PATH}/platform_common/platform/common/inc"
    "${SDK_PATH}/bgapi_protocol/protocol/inc"
    "${SDK_PATH}/bgapi_protocol/rtos_adaptation/inc"
    "${SDK_PATH}/bluetooth_common/inc"
    "${SDK_PATH}/bluetooth_le_host/inc"
    "${SDK_PATH}/bluetooth_le_controller/inc"
    "${SDK_PATH}/platform_core/platform/driver/button/inc"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src"
    "${SDK_PATH}/cmsis_common/platform/common/inc"
    "${SDK_PATH}/cmsis/Core/Include"
    "${SDK_PATH}/cmsis/RTOS2/Include"
    "${SDK_PATH}/platform_core/platform/service/device_manager/inc"
    "${SDK_PATH}/platform_core/platform/emdrv/common/inc"
    "${SDK_PATH}/platform_core/platform/emlib/inc"
    "${SDK_PATH}/platform_core/platform/common/errno_error_codes/inc"
    "${SDK_PATH}/freertos/kernel/include"
    "${SDK_PATH}/freertos/cmsis/Include"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
    "${SDK_PATH}/bluetooth_le_middleware/common/gatt_service_device_information_override"
    "${SDK_PATH}/platform_core/platform/driver/gpio/inc"
    "${SDK_PATH}/platform_core/platform/peripheral/inc"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/src"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/inc/arm"
    "${SDK_PATH}/platform_core/platform/driver/leddrv/inc"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/config"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "${SDK_PATH}/security_mbedtls_source/include"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/security_mbedtls_source/library"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/profiler/inc"
    "${SDK_PATH}/platform_core/platform/service/mpu/inc"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/config"
    "${SDK_PATH}/platform_core/platform/service/power_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/common"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/inc"
    "${SDK_PATH}/rail_library/common"
    "${SDK_PATH}/rail_library/protocol/ble"
    "${SDK_PATH}/rail_library/protocol/ieee802154"
    "${SDK_PATH}/rail_library/protocol/wmbus"
    "${SDK_PATH}/rail_library/protocol/zwave"
    "${SDK_PATH}/rail_library/chip/efr32/efr32xg2x"
    "${SDK_PATH}/rail_library/protocol/sidewalk"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/inc"
    "${SDK_PATH}/platform_core/platform/common/inc"
    "${SDK_PATH}/platform_core/platform/service/sl_main/inc"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_compatible_pa"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_tables"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_tables/efr32xg21"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_power_manager_init"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pti"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_rf_path"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/inc"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sli_crypto/inc"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/sli_psec_osal/inc"
    "${SDK_PATH}/platform_core/platform/service/udelay/inc"
)

target_compile_definitions(slc PUBLIC
    "EFR32MG21A010F512IM32=1"
    "SL_CODE_COMPONENT_SYSTEM=system"
    "SL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_DEVICE_PERIPHERAL=device_peripheral"
    "SL_CODE_COMPONENT_FREERTOS_KERNEL=freertos_kernel"
    "SL_CODE_COMPONENT_GPIO=gpio"
    "SL_CODE_COMPONENT_HAL_COMMON=hal_common"
    "SL_CODE_COMPONENT_HAL_GPIO=hal_gpio"
    "SL_CODE_COMPONENT_INTERRUPT_MANAGER=interrupt_manager"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "SL_CODE_COMPONENT_MEMORY_MANAGER=memory_manager"
    "SL_CODE_COMPONENT_POWER_MANAGER=power_manager"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_CODE_COMPONENT_SE_MANAGER=se_manager"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_RAIL_UTIL_PA_PLUGIN_HEADER=<sl_rail_util_pa_conversions.h>"
    "SL_RAIL_UTIL_PA_TABLES_CONFIG_HEADER=<sl_rail_util_pa_tables_config.h>"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
    "SL_CODE_COMPONENT_SLI_CRYPTO=sli_crypto"
    "SLI_RADIOAES_REQUIRES_MASKING=1"
    "SL_CODE_COMPONENT_SLI_PROTOCOL_CRYPTO=sli_protocol_crypto"
    "SL_CODE_COMPONENT_PSEC_OSAL=psec_osal"
)

target_link_libraries(slc PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/bgapi_trace/release/libbgapi_trace_stub.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/command/release/libbgapi_command.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/core/release/libbgapi_core.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/device/release/libbgapi_device.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/event/release/libbgapi_event.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/release/libbgapi_protocol.a"
    "${SDK_PATH}/bluetooth_common/lib/build/gcc/cortex-m33/bgcommon/release/libbgcommon.a"
    "${SDK_PATH}/bluetooth_le_controller/build/gcc/xg21/release/liblinklayer.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/bgstack/release/libbondingdb.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi_gatt_client.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi_gatt_server.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/accept_list/release/libble_host_accept_list_stub.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/bgstack/release/libble_host.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_system/release/libble_system.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/connection_subrating/release/libble_host_connection_subrating_stub.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/core/release/libble_host_core.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/hal/release/libble_host_hal_series2.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/hci/release/libble_host_hci.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/system/release/libble_host_system.a"
    "${SDK_PATH}/rail_library/autogen/librail_release/librail_efr32xg21_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc PROPERTY C_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:breathsense_mg21>/breathsense_mg21.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    -Wl,--wrap=main
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJzsvQlz3DiWLfxXKhwTL95SFpWpzfar6g63ylXjN1bZn6WaeT3jCQaSRGayxK25aKmJ+e8fAII7QWIlqZ4302VJmeS5515cABfbxX+8uv148+XTx+uPd3+1b+9+++njZ/vLTze3r969+uHPT4H/7dt3DzBJvSj88durzcnpt1foExg6keuFB/TRb3c/v37z7dWf//Tt27cE/Rf+ECfR79DJ0GMhCCB6JHdOgsjNfXiSwiyPT3LnOgr33uFkl0CQHVMYptAODtvNycFxCD6CiGGSPd866CdCKCFfVVLQQ+h/P+wj34VJLcohwL3nGE/vMvw84+nyHc+H9RsHkGV2ISRPQIasclKCoIcOMIToU+iiJ7Mkh+RD3wvvySd74KfoI2uYm1WQYxBvkQBxbIM0RQaiVE6OyuLbElLf3vk5zKIoOxqU4fiRc28HIAQHmNhR6ni+D7IomU1klkBoStjPCPvr3efba2O6BMAL7TQDyA8ykN4btFocPSJrlVYzJycBnm/nGfonzjxTcsKH4Mx24R7kvrEKFKfAdpLnOIvmsRZAHrDzYWpQWgCDKHme1wmAyQYus5MsMmmxtgQ73RoRcgCxsapClHCyxDcvIHWOEMcIiR0nXpR42fNcnVuIIgvUkc9XdRJ4MCuvVg+4KHjLvNRohUV+fozSDAkDcQYM27LROrQ6JS/0TIZDtdhkj9ols2FRlBiLShB86kOIutfAqE8EO+hmvtH+iEpw4YPnGLWXF8Q+tHd5liHPRs5+uplNmnE5PnTJf9e/zifL9VIt4hhjph+80PFzF35BtRT9mSceZpHlrhe9s+hI0ioHij1M/petcuRXY/xQPlJ98p25QfQdRFZFNjMwjAZ5FqEiYY6jWwX8/pcPv97dvr799P4vJ4FLBO9yz8+8sFmY/RIW7s1OHJPgR83gX+8+2NdREEchDLNUOzzpJyi67YAM+NHBhBD4gAUcQeii2My8AP1F7HX6Ips6twFdeqKyBITpPkoCo0LJYNO8blgMRTQvrtMPemGagdCBqYk2gCXKnFa4F5xDpbYc3fqQ/jnBn534Cu2+SjdedVSL9MGxF6K+w5fogK0ZyBUP3MAMjcsysHSUgJsJKsmD6X9Fb6m661vyp/7y8AI0EuYrDSTbDaDtBYfTkzg8DIbblRnxq++s63fWbykyifXghccH6xa3MJ7jIZ7EytbDpf0YJfdpDBxodZWzCDerJ5arnanf2ixDdiNFdrsM2a0U2bNlyJ5JkT1fhuz5MFlWi9Stnmkl3U7de3t7ur042WxPznhXK4uJjnRiubLzEh4h4gB09C3Guz8RgRxvMt6/9ZC6UfgJ7MZJc0B9+Pnr2fbml+1GEIjFLMoTAc2GENsRF16Ey2Mb7pOzLWnMnYYvlt0QKnWLFqJVlotVGNlq2MqqlLUKntYg/HCdkSH/nGYwMMZ9AF2G+ugCuWDxfyxiBX3lX2kHTjen+4vN1gvOytUeVTtSshZThjZHqCTYwAliU/QrcBO8q1GOAdoFtgHWu3zvGKNdghvhnYDAIHGKboZ5ZtLkFN0AcyfIjfGm2AZYY2bhPjLGvIFvgn0AkITUSbw4ixJzSvTEmNAl9n1zGlBwA7yhQb+Hxvx+nyaOOa+v0A0wP8ROYq6FrNCNMPfMmbwEN8TbjqMkM0q+kmBAg+PepLdX6EaYP5kk/mSKt7c1V0cptgnWwDVIm4Kb4O0A5wjNMa/gDXD3UXRhjHkJboj30w6Yi7qaAgzyxxuOvdDg8HRIkAl9INk5Zk6NGt8Ee6M9lG+wh/JN9lC+uR7Kfzi45nhTcAO8g9RcF0WxDbCOE3MNDMU2w9pOvUMIfKPsmzIMaJFkjjmXKcEN8E5hADx/Fz0ZI9+SYEIDg3MDqbG5gfQ5dfYHc8QreAPczcYAJiOA3GwIkJuMAfIUGJwdqNANMH90I3OeXoLr4x3QQwW6KTdxzS3f6iU9BD/b+q3gS9yPczw4fiB7/LQ2Yw8G3rAdRKEN4lhwFwd6Q2YDRyFPfgMHPu+kunOjPqwuuXWDcfSd6eZD1rbQP1bxt4WVsmocqw0p5dq97bcGaPZQxZj+Xdak+bZCqdYkL3SEK1LPqbIo8NhDjI5t6mae/o0oWC0UQQfqH53xuL2bRYZCqDJxIhfajo/qhrf3nCIthyIzBqQiU88AVSamqlVhmLN3d3CascRQ5SLWmDJ9X7bxHDp6FehwshJFA5/Y80fGZPyMKhxVTsg1U+Uiq0CU2WQgy9nzS7x0KhRePqIdb2/XcKKh5yj8nrWvc0p3RMFqoSiXxXPqAN9PVRk1cfR4qyqhEkS7d8wbZxVJReIkyiInGh8C9MMsnrcY74qESYxUKMwa3tbJqn4pQ5HyZe6i63fuKgQ8EQaq3sAq9tzDB/nEy40cXZJt4ZwoyeDT6+CMdRKCG6mwcJYAyb39PcAE+hCkGjeK+96uQRJ1J/nuBPD5CykcC1naqg1mNcAsStZiyFjrpA3D9ALNCJePBQEIeXx7Rt8Y9xBKWck9qm8pWN9HGlIUZiQVzmZoPNaB8+a8rBJOoK7iTQbqf4n/4gvWFTuItoKipfP8Wgq3wOoXby3jxRcwyQHyksqXENZTvASqX7qVhBdfuOaCqNKGegqiVwRN+LVGT7MNIFmFixNc1on/Zh/00WGT3eHBOwjrvNYeiw2Bmh+bCY7UG5ksxZdE+CaXBo1Ol61cuMsPxeowc/Kky5HOlrBRxows46R8HjapJtupugrWbtR9X7dqqLGSqXO8I33G6yLjfQaE9KifpdFBcI2OA9NkFEHn/pk9V9el0EusKQD6RKv/quFfTvyw1q5PtkX2IcmLO1eTnA1k+51ukinJuk1mwHB0fIOc+gmWpTgNwshycp/R355j49sc3J0SLyaULDd/64BYiVIXQZZJDB4TXS7FxpJmBxMvcpHldTEcxZNlmT6HjhKtDoAsD+A4MEau4aWZWtMwiCPLCj5lMAmBb++iEOdVU6yLo3CyHDuZzeWYDYBI8KkuFFCgw8CQZJNmwLknqdeliLRfly4hh86WFHdgSJZQH2Q9o5CyruGzfewtDH39qmFID0C6HWHcJyDIZhBGX4Qha6E+jN4IQ4oXE0pLhCFFqYugOcKQ4sTGMhBhyDEcxdMRYUjR6gBojDDkmoZBHP0RhhS5UThZjrRio6ZZjlT7fV1xjhSVARBNcY4oHQaGUpwj6TlDAJI8fF+FROttSQajG5xGZPNvbWJIJVtTUTnuPN/LnmU59FGk2zsJQ3jqlmiEzPJ+WL4uySF7jkcSWYyJr97UFevLtVJ9EElL0BThUrZovKt7pPHy9/ERP13xHr6y++eYvy9LnjF5TzRtzd03sbWdEsXAlIkJzg3ota6Us3wN3/yBV3tX7G0lRbu4ftj3RjefcJZiCdotx0FJuv2wIQQNg1BTOIc6tSQj6phV4QVWrcZQbt2Vqxi2NAae4/uy+YqzgTfUVA7Ke2EFjHUp8gOsu3wLjjrqZ4HULc8a/4UVYGPOM813+EJ7fMHFmouSVJ0h2lrq7BDwYOUdZfDinEBy2/zchT62W563fDv75LvgL6zojkDT+RijJYdY4tjLg+lWtQAR1GD5dUS8tGJ0Vj76KGzsKIe4CGK4+JyXGN++hNCHmFdP/DMc+3QErLUIl94nzzfBMDTJePJE3uUsOTx8bL4mPbWosOkRBUdZEvk+emCOrY9IWSdLfIFtKDXBejNKC0JuOriCsDOQ3vswYyc44KfTwlrJlhSJpaiGjloXpIidcBKIHXDuORclhrj0cRT44FsJffA8ko6Fj08LRwcfgQ1E06RUNhOVYDGyNsxUKTVQ/j6WUp4Owjcdao0o+rFE7YpcUUSjqOpYAmvVDB9amP/F09lNDMG1JrNzE+9hom+eqBP4onRV/xRPbDTom7gVIHx4cveg0X+VuaewglW8XHW8FZSeRJCtq+W1MOwhGq04jLITT2c4UXYcabnYlik7gwrKRNnpYNhDXEejxyhkfF3Ueio5uXlLrgLhV8vqU8K87FozescZhzGoP8rdZjazG/rQdZOH9Tgi4iPph4UmpSdSHK1tlS5ubbiXXVewEnJVhdqEVhaKo728dHBrw62jOvM/2KurMFG7eN7xI+feDkAIDgJxLouNtpajRWt8uopR+NQyVguprLTD8Fr81RsAx2suos47xn9Mhp5KN4xvp+zMFXqKoSHFgCLmyBtzH8OeY9BpjPuLrKusrdcdaIy0lHiZp3oQ3kTtMsZaG2HPHOMB6HUEFwz/LVLira/np7yIMWUbj7ZuZevRRdZTBSgqvtbVBFuKq5WrzPwAF1m5GYMJtvgsaHyECeqpTHBuw7/snqTl4ZJtW8dYtDnuImuvOybYKly1PF53TJCVm2CaYDt26bkKWYULz3nquQnKbXhDzCfO++nhL3I0UH9rhSqV3tYKASqMEzo2Q2DWEPQiliouEdRrrYYb4PEPyQOJF4t12Y9efMgncNUBrhdmMEnyONMV48r3090Nblxr0Zyu4QSpl9ohKiv7wUuyXL757BmMtEAA39wyKGO2/YusKtEjrFdzloQl2hJt4yvPpNXKOSYNZuMuc7vYdhvINoAsLcYlrbrlC2AQJc/rG9q3eckWWBulLK0+th5/a+NWGaYSiOmM55XToAdLnqbJsI4wmghXpz4jMoyUTwIzkByg9GoRV6E0hRgpCdkWmasI9LXFHbPEUeSb8KEJOcZ0Ma6EwVpwMN0w1SJe9pSZkYpHo8eZ6h0tCoPUGyLM9DyoRYVhmU8S74bWqg2fuCX8OE4ibBvRGI2BJhupTZVSyZKc2ua6iZSjaErQbi/VFzb7OFNTY8NrVk2+Xhm04/RNMS/+yCGjiII4X9EwJ84VJjTR21WXWwG98D42zqV9HFmj7JIKlFWPvOPoEbVciw+8e1krlG976RZpS1HFoL+FRXy/vPuILUdbVqqeDBicm1eECtGohTdoKtT4ew8gYyd/lNdoWuDS/XbqQxjbfhTF5lxfn6vUbHvuYtbhi/u25tCjFmVOG7Vdh2LqqO1V5azI2mtwS6MRaWuNFRm1XV+40q57WuxOQ5gesp75gKFKZow23/18su6uk/cA9KqDRxzjAm/Bw8LdU/FZJLd5YbCosWrK0/PURKQdw/SsHurii9KEkcqBlaaOXTxN84cY8h4mIZSe4x4iWSPqmiRsoEq2C22ePUiN9iSnV4opF90l34DVadkmtE7zdnBf+NxFVf0UTVTOYjTx9FdnjSSN1xLNBp3L5dS7eRR/Z16wpp0ZNSf5tqtEqA5GtzA1nQWuMMngK8kcxwThFrgR5nESIXxj3Gt4I+x3uUnyFboR7sa8vI2uqaNuw8s3mR3aQ8Avu59utDbqRipTBbQwtZeoNqJd0FV3f7kLffC8nq6v4CPbIBRvl41BjaWn6SrwbJAED5eBfUD90a0+mh3Yl139qeUlaxQ1D632NdY6KpJ8dhAYiKQD0rNuaKqQoRO5wrPgxADlmhUu3gplHUXLMFn4EChfDKbJ7JgKzl4Kcl94CFxYHyMQ23ehNLSRGFIDK41s7AMMYeIJH7scslUDShc7BzhHyVrU5lYB6WImEd4O8dKX0KSEs/c+SI+auNVguhjKnPUeIqfxZDfBi3a/Q0dLk1Ej6eIWg4OWSlDi6OKVJcDRQqwC0sUszzxf+FzzELMK6AWfomt2ZOW+F5ygWXxeoWEhHJuPA+vqL9U5amRDOxINdquA9Lf9Gti1wLS2/RrIacyI02yxNTCrkbS2/RqYlTh6W1gNxCqgJVrY4o4KbY3sxLUZ01YpAKwO2DoGfyrjet/byY/rxbvB7lg8kFsCILyJpzYRBEujR8UJciUi9H1VGlCRBtRDQya5V4uHZNrvHpEgVfMP+r4qjTiRaFUbNOj7qjRklipbPOSWI/tE6P1jKlRqCFUyUotxLS7CC27qaWV0NZ7CvRpWm0xiNhB0NJ4qROj7GmjgAU8MJGYM2mwaMEqk8LKaqn3aGKo2AmkKEzX71BCqZHa5xHRAy4FlZgH6flOcCFLymQpCuY0HwT4P1Sp2A0OVzgNMUomD4S06DQz1okok5rZaBZXILN0MEpGfpu8Qkp+kH44gVfhAPe2MTIrLFg/Ju1IGI0gVHvR9DTR09E1tGB1hrQob+r6WsFapvaMAGsJaZy8xU9CgUkNoirEVyVAIPWS0NHh9KD0DABVOwrueZpifEdw40Z/fSZIwstG/ET5X6wrnEDW2B6PLS7Tk6E6MHk5RmEPo65iqY5hVeSINX3SAgwjJHIblYWx6O0YH6cWMiCl3SWcqL4wQjA5naAbq1LnyTYEO4xabqoUra02/tHEDSHFsTaBkAs1hUloiToolF0kM89IUUtRoEmEFk5mO+KKFJhtjjDGUCTbW0KxXXinYpDdsQZv1JpJG/9bCq8bS6N+6mAnOUa/04usi9zZHRKn13mvVCFZLZEQ0j9LtVH6hpomYwdEA2IsKkLr8WW3sqDHKWGkA7O+hmojVj+to4iZ5xnsfQ8fPXZE7NwcS9uOZoNHkf+QxC3O0qECr/yZ3oQ1RmJofZjKQmBTuEMj+wLsx0ECFPaU2IL39lpLuh5FpK6beB7Gpqq5gMjwLztgb1ocEN1+SFIzTCOKzPm9EBLdemhasWtkZVe3r3efb7WJ1FDWQEyYj/DpeQt+SLKwotTNvZEf3kNzGO1pKimHT2yhPhK4a7iqGYzJvZMdiU7dCmNV+y7wfinU6+wTCySw5vbeKxAoyXu2peTXIomBkdFZqYxUELSrNql+TbfmSKM+8kD3Bw5LcfFFStgvjBDoggy7eWI3zRKCeiz0VwmLChpHkBR9gmNkHpGAszqb7siSHnxE8rm3C8psvSsr2vZTd97Pkli/JdoQwTcEB2rt8vx+JvFjS+68rdMhxEmXR+G1xTB691xV44BE88H07zIMdHFlTHCMzgKHA6DEBcSxLpfmyJIc4SjKw88Vbq+aLsrKT6HfUvojr3nxRUvbfcpiLK129JSk1hUF8FK+L9WuycjNALmtGXYy4tbsvS3K4xTA3chQ670pbIYEgkG0Qe2/LjgZByg54WcLLl2Rl4mVjcbPXr5mMtMuWRH7+7QYGNyAUPYjRsdERgthmnxfr2qhkbVHhVv3+XDNtv1xfqy6Vv/96Y1/fnJ3Zv979q548mmEU2il0cq7ZJs6iwbYWLxhkHqupn1VTs0pEbamMidSUPZ0vzZKCaiPajBvsh62tnTRDgFZLk86IuznjtnUFq90ttFOloPqtOjHhrmZb2d3HlPILuJvl1vM9Jwo/gZ3yNia6uUXHViY8pcSZyp9ZwA3NLErNGsZdxy4mgYBkeP6G10LNFzjipJGZEV6J3ZeEpZKpBV5p5cPCUorREq+Y6mlhOe3InFde7y1huTgo5y+06mlxOUUYzi2oenxMkswCxfSyI+NFtcn0eqVh0gTFpDqdTm+9Z3IEo7j+UrIfXYLpqFiuhnTflRwgVjABuapTlkT19trWLnZ+DrMoyo62D+3Ac10fPoKJIYr8NpHemweQZTbNv2e7kPzwQrxXgVxybEcPMEk8eQ9KfZtXBLNsGSYqN1Pw4luCXNbmKSRk9bJnO9hBN/MFV7tUdiGVkhX2IZGbguMoROGBcs5Rv7SAneYxjgJ1Xc8mnTOD4fpeRRQ4DvRhUlwczvLzbgE3E2QW31hNO1p9Q5R5NsZEaxuYNYVEQejF+HL0kL2aZEa9jmSt2sUpWKLkhsTONiplVTq9d9qW6jPjJg0WLa/vqCVpdA5SSE7yHGfsrcX6dGgL0+7jc+nRlba0U2u+UbhyNYPNRHnbRi1JmzcAiDqLkeyymtg3xGij7jjBHNQbYvRRD4AzC/eGHH0NCKSza4Hhjp+4fVeYPjWOYDNHGTTl6CS/vbiciX5Dkk4FLjbbmRRoSNKmwGGe1udgoPWBzu8xuIdz0O+I0qZCdkwgcL3wMIcSPWGGQkrzEURbmG41HoCfj2yp06tGLcxUZGxcj660tS5ClsbqT8lg/m7iPQhfp8aC1DvgLAycJSH7xKVEYdZKt0Y4pRjt7ljIGr/WVJ8aHWmmtJk4VahdH/GDh1waofCUHsiyXRjD0IWh40GtMxwDeo1I1d2me1lqjyYu16FRT5LuMqJOsMs9PyO3az7PUEQMoYZ0Q/DNkdJc2vXFGtQP9RXeQzE7Oqd+bbGG9AMoxJxNq1KYIV0CwE63q1sVKsuQJql3CEGWJ+x9I7r1aUk0pJVDcjbMplItTrc+WQLCNAYJ3n80s26jomfQ8zh2N4ZJLY8K92gI6jhPmzgieAYdZ2kr2XJNajh3lz0uW7emUQz+ls/b5Q2KNKTX3IXHFGu23ObqLlhSzWo3TwM6LPOlr/N2t1KlQAFusMi8MINJiC8uT/IUn25PsygZux1PrcTwpCP60xoTK++OTKdcSMsp0Zo1JZlTDatUyVBoNOQrGLOA+7Ns5szAlDfLrJ5ZvUakmpqF3UMy1DStGUOiyZkU40XVEWZ2pD6XNrW4eWbx5tKrL3aeWdg59TO1TaY32zaXUlSWoQgZX/Qyno5Imz5DEg1pNZ7URrdGwjlweLVpjuRnLCimWJP6zVRkgyJf3I4Dj26XWOV2A8rNHjkZKF6cpcZVLt2mjJc+xu7VDe1bbyrzlVXByPYnr1EsxrnbYkcr1auhtt1COG+aE/lrrsNel6WdAFSEQPOejraMesPKiGyt7loCm9oywNCPIVbv8LYtW2vPylds2huXIbPNoBZD7FobnpUmR+8WiJ1OZx9QSD7be5Xn4PCI/wGB4JSqVieFpC4IlDJlgsQD6hQoiCSHnXcIc3beJF4WNYwsDz9y7kVnhZhsOmCynHLPd8mBenVGLSjZjMfoh+9r8JkmkCwXR91pKIYsgyNA/9ueqtNoAClxiSP/WRObEkqaD8QVgBzC1sCoDSbLSU/dVq7VjshUH5OF4Bxe79YGbEwbuL/naWb78ACcZ9GwjkltHFsn430SBXhWxgznJroW1nj+iIAWAjSzHkDXxjrNcZZHmJljPiBBC/s0ZWc5kmNLEbWwe7o4fauZXgmpxk9jpVKrQdBxNVCpUKRZkNOWGnhUONJMYg0sYgUGBw2R10Ep8irBNcUXfThZXvyr40wuQmvePfkXGghcKDCoLjPEuQmVufTQVFnlmafeG/TQpG9k8J83Z6fqRdYEkr6hAa/gQ5InKVWflujDSfJKvBgG7uZSfZDVQpK9V+AINspEShB5DtuLSx0sKIw8D/aVbwIsVK6AKxJQ6GBBYWTn0dJQ3S9KEAUOj0iOeqvbQpKduQIpvDxXn7WqYKSj2SAG2evtyZOGaLYJJR9dpxnAGwV09I89NFlWWWK7yU7DTE0DSJKLC3e5OpEKRZqFeifoKs3Nu0f1KJtiyI+8jjoGXkcVDmGWRLH6fEMDR5aJ0DZ0Jg/RjeYdFsd7d69MogSR5YBTn2lpLlpIkmz8QL2mUgzZURcMouSZ5pe3ge9H6tO7DExJhiHMkCDnHmbqtupgyTLy0sy+f1RnU+NIMok89UE7xZAde0H1lp5iyDJg31PGTUDl1rL43kk1xPE1jAIPDcPxEkWBxZUWFlca5ky0TZeocEmBpqmbBpDsjISG2ehEaS5ax4qG2hpGivc5AeeoPoJpIamwIYuyaY5Grepd3BCgCrcouvc0maqCUuCD73KC/NvcxvjUUJJ8qgSQynRaSLJsvEALlQpGkgc9rKhMpIEjyUTL+qTiiiR+3XYS9UavCaTGRb32NIGUuKTqg9Im0DQXhftfBQ76d2eo1Lam4DPe6jtQip3jdJkd5Oh3GOIb8+QHEDUvFqwWrnQhXurE9TRlBrpO5vgUZgy8RPBIFzf3Pr5O9ulzGIXPCvMUTN5N5OX2mGJ6evaXFjqWeR3JVvpUKaRrWG4YVQ/TOEFdfuY96GXaRtXDVPKYOAdb+ZPgw4yL9RYdDGskVUZK201ajFT3shY4cslBRohJZ/+Y4Bdm8ClLNdfocXS9zPXXm2kJejXQ20aNo6sxR4CJ/CRLg2QFpMZHcc9rg5D63tYCR3lyrsFJw/xceXq2TDChg1YLTJGX94cep6+AFPlkSe5o6dlqJDVG2sJqTfGz4H0XI4RELrNQPb1YatQZ9vreLgEJz22fo5tFeA8Rl8agYq0eCochGEsBshSaANLSi4l7VQoVijiPcu1AmkIDQFh6Pb0pK76FICwf+N4hFDoe3ZXfQhCWX+wEq/IOSrMYwBHnQs6aotgnEZ/Vr3i0MWQ5qNujjyPLJYjEJ8I6NCiEAgM7AeK7CvosShhFJsiuDyBFUYwmSi08cW6NU8kaPIeFJs4rtINcgUj1urBkerJUaXhf9bPDWOKcSosqes4AjiyXxwSIHzrq8CgxxDnITW7U4Q//VMZY/GV7QSzvo8NQqoxUqzAbTpxZJj7qq2hkvEtPA1uF1a3QhxFmAp24Tokscm9il8sQkCQbxeajCyLOothya8eRL182XRBhFn4QSWx6LMVXbwvLDVypI7Sl4Pp1GclK7XXjfXHZcSo7GV2Jb0FIMZDbqt0kILBNe0A+HmdJTII1CdQQUgyyBDjyVb+FID5OBi6ODKWlN94Xl32v3h10MGQ4KNW/xvsSsuWOgNWyBQ5+MeZHNJTAEJIwnwShoB7UPkIfZ5aQZjOAI8VF2SxdEGEW3X2N6pRGEeX4+Z7KJFMbQopBEQ6qes0gkhSfwEvFz5M0aZQAUtIR5uZMPZochlJgRO78VGdTwggzIXvmlOtPD0Wq1S3nHAq/V5me7iGpzI1qm/zqgUnOY8gvoQhcKjUyg6ImvsJQ8BENzqHIQOzirBEf5b8Ma6TGqLnFIJIKH7qpAhc07jLsEK/wgszjvwBvhOIouArr1I8ymWzHI1wHIJUY0supdDCroVQY4QxMGthQGBUm+73Lf9vpCJUSR4WL0M2rI1z4L1JlcxG5dnKECvdVkmwmJGGYBioljgoXfHJNAxUKo1Sn9VRnZYsI3Yk11Z+pRoByGU7Z/ZkqH5UV8gEcVS6qc5NsOI29vg52A5Bm4hL9XNvgqn2sBn7cyRIn+lgNVEoc5T5WA5cSR4WL8gCRgaXESWG5qA+jGoFoYMKdKHoiAtFAhT/16UgEAkI3CtRW49lwqrGRDkaS637tqEYDkVS5rLrDOB2k+pA6RoY6mPHdgKzx/pMEeL7Ns7u492YRuIjvSE59GwtlmqvJiO68sRrviM/3Fu/awZ591GFEZvmetFyQpjDJiuVgFO2NZYUbozEMI81qfLf+GBGB7fkM2ZP3Go+JF7uiuLuGJup40l4n5XJK/qbD2XR6mqSbKfqYvIMJeZfMGY7yIi+Za6J2Ps/tUqO1DkHw2aPkaaE3rM7bsgmP5AmISZdPLOFBCN+cbjcX56qGrpEE1a1ftIaxVKyvg5UUJfkieQx2ufTNaKUFCYigyuQdq4egYn55GqIc5O39xyN4UG5mCIigouQdq4egYm95GqIc5O2dei58BP69qslLHEF1y9esIRwV26vykSBj6Nilc/Rime4a7pOzrUCxDr3+dNg+Cd6dy/APrIWdxtDx9iPTre2YCL1iERpWRcZi4vE6C9tldFFU4zfbHaWMcseJmw6Qb0w9dEAY6Z5AH4JUuhUvYUqLbuyD45SgJ4CnXKgSVoeRNQm9WC2P/fzgSVm9rBFkp2mRIsZDsaodSycpYyNytqZEF4sNM/KV8f6uKTkG+IAbzS6oHOUNQDKXdift1cYZ+07keuwJ5hlO12aOdA2viW/TCtKeKWBp+ZikZwr+OQkZQwtMXWirSUXpqgccGz0BR0nL3QV2HD2SOxkzLzzYAYhj/JPwtU/R90rlUKhddf+b3gOcBJTiF0GZm8W13iyh9nZxtbdLqI2DoSBykashs6/ACAw+i5lkVfZY0hjr8g4Z3+DuzbjsRuMVDdZgI8/XQ2OT0xVnnE3By/TEuz1YhfCxhzX1vbZYso8sX+riWszqB5mnp+AzT6GkM6/3gbayRFDyhTdEbM7iSfaofciOWoqIYskXEwUY/FBXcZVw0kU2SnKWiVux3S7VVpwUlq2A2KaXMgWc1GQRFS4/TEuLCZsohCF/D8Jkw2UBfrzEkQJieWnNb3qPfv1slaOv+tJqGs1qPIkIWz05YrEfrwacOf/0qCGQH1BKF94Db5q0ETkVJ6VPea3jXAo15BnSiO8IlCZ1+M9JSenSyWg9l1Z9sQb1O4LQ9bnScmrUrinUkG6pdwjJdqrZFGtJNKQVyDJIDpfM6I4dmRo185piAhTD7aIno2qxBMroJDjl0DZEd/9XaCx+mdwYLmVORNjqyTHk8y7ceyFPMm09mjTlGdKIM1u5Jn2EU5oLasN3saUmZUQvvxRthSZ37+pQiCnRUAlVCRn5ks5oKqqeVFNlxp/FRleZiWW8kSozmo2XM6WvpiLrCjWl28xaGdeH89i6Ln0EzrZL6VOOEudSqCHP5Kh0LnX4TxZL6SJ6k5MmreSvd5LQrxogzqldU6jxUelcirUkzjAqnUuvjkzTo9LZQouGwNlGpXIv9RcIPDtGKttRCnjOmfFA6p3Xb/CznSD1UjvJonSrdcqhKaSadWCK/TubeGhoqrXGtIxaVpqWKK31f7i45lOoK3atDcFsRxYYX7I+bpcoiMtUdahzv4cu+mgPfHxMoSpO/MI76/qd9VsKk9R68MLjg3WLc2p4Diq8W1La1sOl/Rgl92kMHGjtEjRuP6YwxKWOtztRMd2yGiBznIfMgON0T79A4AbwJHDNE2qImiD1/pcPv97dlqQOMIQJyAivLMnhINNpm9v7BEJcn6gn6IBFNfqAohBU7ZMHz4EoOCY/8BXSSUACEzt6gEniuVCjVBQfhEpw8IncMeh+QQX0Jy9AzRUtHNsLDqcncXj4wWo9I/L+RvH9reL7Z4rvnwu+XzmrwDtpVXNs1H3Y29Ptxclme3Jm7fwcZlGUHW0f2scozVA1JruSdtnJE/p1XAa9OxJ/pbXmDrjQkKhmj1jUhLTuBX8iHyDJSG4UfgK71Prw89ez7c0vSMDHAk1CTnUnYpFFwUYVPcVNX5lVAU8W479pVgl1CbVG9G8SPwmj7g6oNO3q7Gl92l0HGm7lbOCCuBgcyYJWvqimac+lNeDgO5uTyPeLAZRaqSawLtMikZ+1y7NMWmEGNO0jLIfcOdcY/pkWQUZQwiKK+FOrzxNI6xpTlq/wBcjXu8+3Wz3NxpABaT9upJBg4CYPaoZkIvveTi8kpYlCmDBqZuSRlFKGYNY9TELol5cdqyAV/iDvCV1KcZSQHfrWL9fX1vuvN/b1zdmZ/evdv1oh6l7IWE5GTKv1CjzX9eEjQJamBuaNIrW3dIcY9f5aXSaGCVmcALKd2UTdJAtvSR5nZtvQvhi5dlRGGwvgHb6aS9qHLm545IzVzSE4PbtRZxvMY1ynrGIJbknZKMqCKZSJAVkpFOXbLw1K6SnJTjZI/R4ewCBKns1W1o4MIzW1IwMF23hoZUqhODcRdYQPwZkxXOkKPmGL1qEpM+Zui8BT9mV2UfOSUh/C2PajKJ6nGcHpXmmXIGfLgeSFqijNjHvasJoZ9TRB0oxwmtBovjPFAhhIQ6SNYZ0hTN4zZVdFtQ9ijLQcuF8GnmFwuf5MLC+PCQHdHDtGJJS5RwyCW438JAbEDJzONiAFn/3VD1udWdXv+6hbxHe6G+ryG/hy1Uu86/VomvX5xmBlQ14KVtRUYXVbfwGiV33wzMAOgJNEP+Fd/B6eP/lWrZ1Vaw7vTzenP19sth9vcKZEfoDbT/b1558+oH9uvnz+9cOvd/btX2/vPtyQlbcH4OdkXfA5zeDQEF4A9vrT5+t/sm/e//r+lw9fW+it6V1hIRX++7v3nz7/Yn/5+uEW/a1G9qcP//zx+oP95cPXj1/+8cPX959ahOmEVj0zpCbs568fPuAJYPufPnz99UNbVDmdZxfTeWqCfvny8XMLHc+WqUH+43tSBjeff20BH4FvM0NpQfgeawyuzvzjr3cfvn797cvdoE/25rFEhF3f3H68tX9FLmT/88evd79h91F52/7HD+9/+vDV/vnjpw8tlv/tb3mU/e9iaSNEPmk/eEmW4+1DxTciYm/+8uGnu0+3yEK//vzxlwFZfva/G7M25Q70P6mVws2Hm89f/zpYBO0JCjUxXz7/C7LfkJRWtCJjry+37+3rr3/9cvd51HSte8rkTPf1/cdP9qePf7Fvfvt09/HL1893n68/f7Jvf/vy5fPXu5bEU8Uu4MOgrZo5DpS6gs9f2wbCPaKMMX67Q/98eV8avqgmQ17bjeHl7V+K/PLpt18+/iogss68qCT37v1fPn24FdS4CPt11dnbTx8+fLn7eNP1jioCVYX/SCtUB76MN8XgPyL7/fTx83tktK8f/r/fPqLwADn37T99/PUXdZ5VJWQQ7gSsio3Y7Ydr+/NtJxhp7E/ugdORzs/FdqvJfRa73PNd6+Dg6cIkg0+vg7Mz+kyW4J00jdzDjY9tBLkbyjisRX71LY4nQOj2SdAv5mCQDNiA3IRpXHYRc/alF5+blw8f8DioJ558bF56T275jZzo7k4gvM+A4fzlbTZNAvSOUTXR7V0/tfSnYm9pJQ7vfkQDQ5ioyyO7lRh6phlw7ltqRqHrhQdXsmZzykXfkgJtSS4/LDajOr4n7WP6WOBhutkyAI6D+k/b99KsywO/ZDe+V2hx5f2BvrBcQZiWXMxydEUXn5qUjZqBEDpkX0yaI0ScSXTQA4YeNO4KvU6vZiPb7/EJRsP8Qbl4+I9qowfTrVHxTs8LC/GOUUccdkIiWcETzdwo0RFLA1f0Eu+j3A8OzT0OPhhGyEoDDyPL+59jGmHjPz6SIwbVpye5c4L/co4AX12BHorI52OPnThx3h3G0mKci8G+w2AfP1y8TodW3s2I9yOAOqad15mfS4bOxPAwwDPueBfKOIHyqZNi+yLZwtliUBwdkWJADptMyC+eoT9uncSLs5b4f0DR6e+ooW7UNPwk3l9z4s9kmn0e0p6i6DFSXQYS5OGCDCzNIQRhZDu4/dPGAB+/CHaTFKrHTHAQcFUD0gXLIAq8zN4nqJW244jMri/lDJENn3AkvaRDRnaSZd4CjlAesLsBMek4l9HfQVErCF3STzT7z82bmeQ/PTEY/K//tbmah8MjSEIUv6cnwPcXKoaKAnzKErA0iRi6IMw8px3QMI58Gi0QFFKQsyHpUlTwE4H3Bzkr0Z5T9v6YoZEwIV40bIC7/IBGSg+wXTlcuAe5P7SjaJhEAO4hibtAEpygkclJBpIDzLosGI/1IvzXAfrkR4k4X5FHdsyDXYcJ/WweAt2BxusAffIjHW68djeXsxEZHHIgOvjz1+jzH4WGHz0xdR8xyah+lNWhvU4z90eRXm1ERhwLEMKJG1h9XEFKqKPTTGso/Hm9D6PXxaeLkWLEhYRa87t5fasM2WzWaBc1SoFAz6TRbjNSE7FY2ZPb3dDq9b+QT+Y3lHlGUvbpx32v/4V+tqCNjLISsRMzDnr9WUsrIGoh03xEbMOe13m9x9+9rr+b31CzkhOx2vis3Ot9+f2i1luEpFC9HJ9Ler3HD7wmD7yuHligui5DU6gWM4ZZr4fOPZqvtkbZiNiFNV/6Go12oJP+iL8/Ib8uYac52A1PFzAeYy+FqK2AKLIidlqRlapwufjbDkDcZvZ/Kd63717fgPjHf/jvn3+7+/Lbnf3Tx6//w/qH//7l6+f/8+H67tf3Nx/+xwl5mZN3sRR8gtO20aWpLmV6pCGK24EFWQrGObPA6eZ0f7HZesHg8RI1c3kpK2UnAf7kpVkFXoeE/vevXz8myEwkE55NrNb4MECBdeT0PnaGP05g+XlPOQEmAVk7FQbA40t/aHcon+iDM9YTW3XZCJYa2e3zX7fYxC2HGumT1PPBLiVVLfXOtkXj7WYnxcZ5l+z5ICvoJ4cwP6mahh2g+SkbBm7A1c+eFA+gVnTvgwPrjvq/iwIwXW/Q23jM+Tp5fEIV6BDAMNNSgSTcAHXqAo5Any5d4f85wkododX/+f5D8F+0JZ0EaMQ9xnqzbiStpxCYnjdP71ENC7j6j9b6Imo4sMonUXaECd5UrFH5yTeZeeLHpAUwTZEVXvswPGTHH4fOuM3UVguZvfn8/zM8s14yd1TJVcwn9EcF+frRy46vyTjbRKv+YqibC1BF4RwvcXIfJC6MYejC0HmW336yHq1CNGJyexMOYhtHVKJHDarUkahgEf1g0amF6pPvfvjzU+DjV4qjr+ilzckpAUFoET5dhD767e7n12++vfpzDVROUVSbunPnJIjcHFW5FGZ5fHJNzl99KR77gmz+F6JEN8/3CdmJjmAQYAyT7PnWQT8RXjUH0i2RGGERg9xmMP4T0qj19wKaatDRMs+Sbsq5hVlGNlCtkmTuUGNq8JPunTN0lpPV1HcfP0l9smEkg6M31XSuSThxEqc8wu0kBWPsnMjmVXX8NnSFAqPD57yAZEZvBzFw7u1ddl0oOX85texNjv25uxN1Sw/jHuVxWWU3loKocyZhvOl+9f0rOtlsf/38+e7Vu1f/8e3V1w+f3t99/OcPdvOrb6/eIdc8+fbqP9E7tx9vvnz6eP3x7q/27d1vP338bN98/um3Tx9uEcC//Qe+nSWIHqCL3iF94vffXlH1PxS3QKB+892//Xv98S3J5Vp9WjgLkVg607ubG/Lhd8gjw/Qd/fRHpMOrY5bF7yzr8fGx7ANRd2ilqVW2A5CknUBP1oXwjVocf+i55O+uk8ZeSHrLQe/E78Vu0AL6E7Fp+B0tHpIE4rsYX/aWFBJP/if+16LPVYVRqvanb69qiyDlMe5/fv93Yk2RrvylGLde9Wo0Id/3P0UNwGrKgafpfSn2X41R/97cmqYd/zmBEOcru64uIf6++q6+mqZxR3H99S7DvxQ1oPgoT4oLL4tvms/iJMw2DS0HwQZSKjW/xrcM0QQdw19WB3KBiyKZzEtbFysznuV5oDykzXo2owf6qxttRp4kyd+4vraLm/U6TzhZ4rPfJ9+mzhFip0nsOPEikhmR8UIrU58dpY7n+yCLmGZrP5/hWWrWk1HC/A5PKuNwGflUBtJ75mOdzGSMr+lKN+upVtIxzqcSeBgpxHY+VMZDgwmqxp7ppHRiP9rLxsrxTsasNL1MqawHyZVg0C5uHsKeerrhe3T8IR+65L/rXzkfdL105NkqZVXjidV0H7nz99Ab13FPcbPc69tP7/9C7kJshERf7z7Y12W21ZSWE2PvUOObZsPbCbJaXx27X1WZXW0HZMCPDv1HSGaj4gLtYvfY2Ne9t9s+7YX4JAYySB+H9SALEfv0NFz7qS6W12krbfrV9INZAsKUJLFlv4K7ZeoG0/ikD+89tKIqeAcDnKoX/r1UQmxhOn/i4e9WY2oq4gZmAG/Rfin2bt3uih4ZvH508JsN85st85sz5jfn1TfSl3EWzjDkPG0V6bXA31dX/37fv5B2FZYoL5b9vnUv8KiJ9CZEVBUllPtQo7CxNIfaxExnNNQmaip5oTZBo3kKBaQ070+tBrK0qklieFIgA1ev1lh259tJ7G7exRqt+MAmJwCEYaTTNwpJKS436pItsmXRVoav6RVP+ygDXXpOZvudCQB5qGIyAfj+Djj3qR64WlG9cHjqSBNFPDcKM2mwwnFKMDwEl3WXPhKZEfExORHIwc5f7G1tKSw1iJ3IVmlIQjM/qg4Rk7kvjQvp5ludSWCdWlWTwKlEnhrE6MnZqYXIRHpODTI4M3HqkDSedFODBK78mmJy6p6WJ74af726xMzz0bsqYHK9fgdEOsDrQ5EGVAOlAof0ogoo2XMMxTr0DgDd+yIL4ZHybnSHaoYp4BjLWJJo8r5M3qezesJR2ADO4HqaHJr7HILAc0jH4+50IMInPNGEWsIqINCBSvkh6ynBoHaTzlST9SI1rPaapRKWv3VArMNOMXhMNDs+vtYrcpGP6IVNn0NHGqcK/HstsnDYX0M1WlJJFFYrpgTXs7oKWr/1UEEbbj1UENmthwpqt9orYXWqvQpWq9qrADGqvRIku9qrwDarvQhO4LmuDx8Biu7p/FM1VsLbF+guBi/Ei3HFHpII0U48l1yzy/vsVEtErpazrvEY42Oxt7T4yK5ONMkC4GMIsu9yxl5D75NtJmgcIPFuEOc2SIKHNxLvZn+QaRxU2/lexturth2to2p/j9DLqLvIPOde5NVi7Qe/iYdE+OUJz618AvvpwD3VZMm9VII+x0WIhUk7sR7mBM+iJjRumv2pWIO4RaMtVD6fwC61qhtVKwtWSTBQVxfEU7yVZUyPS1RF7PL9ZOVTl5GAYAYhmXFNnCA3LQK/j1pn42ICgESlJEtPNNl0K0uLfd+0DGi+bPaorTFeMofYSYw7Mr4zdw4Zdhwlk/2cqqDjfoZiOe6fjMvwtsYL3gOueRkOcI6T8aSqFB81YXPIeNoB4+1jKQdP8nih+V7fh2Snq3Exc1RMf4aK6T8cXNMygtR4xYwT456FRNipdwiBb1wUiveMWyyFAfD8XfRkXJD56AUN4Jz95ISjqpRZGpZ8lpYlT4H54OXRjUyXSTNhoyFRQblVzwh8sRprVwrplUKnOMipojxuSNE6g1BK6aoyIaTcSEsnZUqLlB/bQYwPIE/YYwqEYzqpA0G1qWejeNW4h0kIfctJojxDkY7oe8VM9gG9HU9uc+q+S0/EV2cWuVXuvH+L10pu8F3tk10cCwJkUeBNdl6styvjSb7vwjiBDs4qUMSb5LZ5aV1aRSKJgReMZN+lGanwTNZ+uudhosR5sdOVazfAGAruZoHv22Ee7OB0wDUGhfPoxQoYePDNs9bLfD+JfudZtGe9/7cc5tLCUegVH6XLs1jQDJRqaZolEASKjoU3ZUq/i2MpYfqkMgm2jaWnWL9cX1vvv97Y1zdnZ/avd/9qhUXy/zxpu6T9sLVBGhiRQ+aMTAGbJI2xBQuLG5u4sll0vsUYpowbGNyA8GAdIYjtM2kjN8OnYrNeYOGFp/bxZVH4oikSfKndAAi+jCu+cIxCa/zEW2XEObHMViRfmCpPXjCukIUTbDe9Y48TCV8zZTs+UtXbew7XbiRuZJ7awA/GtUbOCQdRcKEJKuWJvXixMpDlk/0VH5hnomjpWjGtGIq1jIKlPP0tL1YRO4o2ADbqk1Ocb6WEw1kZGvlXGr8KWnASGVtTBhz3Ox0bwCTBF+/h21ZJ2afEE3qfqgmp6mMyGZiOA5XbDopkJaSbEii1JqCbeA/k/Bc+9l+1kOQvSYqDiAQE6gQutw8WiDqUL6tBi6oSMF6ELC3As+jJgUZJEjQlbj503eShZIf+UiPXhqM21IVKlcZwOnRuF7Q8KgwwWqNuQ9xGSGpcgOFcU5bTyDvFt1F3GhPTw7/oQ7K5FloF8GiKLY2IJIGlUNw4hXgEk/OdYmj2HsUYR42YONOVRrhoR1Jp6AOM0QBKIxzJc6ARD4cYsr18Aw83MaS6qbQsLSRa3fTh1RntSKxVJtvWhl87tz5M4tz64Khz6wMkzq0PrnBGWTycjYD0SoFahNxC4trpyAckX80aMBybIjlh6IlHLWiio/cRJOmhQg9HuTts4HHsd+SBUQiKWzgc21c4YTR6AceGFx6YBAT4olstUBybVnhw+DZzcCLho87akHT6ONdmEh4gzmMik1B4XkpDk4e7l6olV+lcKBDmowEG6oFRGBm3cHCTogEmFppQZ8KQmqsBh9Y3DUhF7ZADwkfc4iNMQJVXCgeL8hHBMJ5C5zIMqNTsMSHl278xSMWGsAFNZ0sqiyoXeQOQWlQzpLyH05OKVitfdDVt2/xQ0q78ArgyS0hI8QzqUU5LtwToLIkhAUWpT24CU5fDc0BdjxRzKnl92xnwgK6UUidFUfT8cCmr3AKJTEi/qVsEYkGyz/GJY5+joNwANGTis2zKRdWRQNuDMkO8wpQelwCOsywq8Ar9MBc+x8ElFfjaqeaRwpcSSEwWbWlaDqXVY9sCsEMZhFcIQ7jwGyWuJsULM5gkeZy1Ch3gdVyydzlET9kPXpLlys41LCrFyRk7X2gXRI3X+0JxZXpKoKddtfZtGqUB25/OIIJe42FCktcXlcGwzEqDs3vqlRonEb4uoSe+/NyQtNJBOtJIukPZ4ThDJnX+jpOYF1GlAEogfo0rJY4OseTEx0xyynn0GcTRKjeLpAwkB6g6khiU1a3eeqvXsAxNhRTnVWMYy05vNsFK4+MzEarReWvvb0mzvSFYjfC0AL6E5BJiPIOK4DIoN6z1r5/S4DX84mBwbk6WN6gbvsTsAV/Yotuk5LIo24+iuO+HunUckUVdck6JWqZFJkR2C1NPKdLb46o2Dt8kp2GCjwVL22gD6MVRAU3A2PjkAAKB1tQzNsFbpjYDW5paPzo1tU5gz5SLtOA1+Uh5JV59WKD8RDe0ZwS72qJfQasWJRuaLqDJr+hyC0GDqRmkKKx3csswUiZeR4qiO+Uu9MFzWQOKv/RAUptQSDUrDEGSFJWXAcmveTuOTu7y9L1dApJnq75scUc+byTIJ39Xk/oYufx2Kld+S4Jz9OIiP4VVgj0VT+Bv7DSGDj7zM2XmacyUXlOqAEtvDUKfyb5X3oIscIiFCbWHIMsTBYBgP7nWzXyXa1p86G1aDAqvarJhiaZixhJD0pLl6+LGjP384NUA5Ord8o4IH9oxGPlKWVBxFzHdR5WOfTfVkukUZVir4mZl0wrp8YSKbtX8bXoPuLugGFulMCO3zwQgjvFP8qZ9ir5fA4/NWohs10IEd8kBPg97ioyzUlpr42TAUIz2QVlA72L2qe/VmyRxkcpaZl7vA3U9hkBVmdL77Ac/VGY8Ci7EvLqH1IfFNxypftgIJR9pEA9C+OZ0u7k4Lx6o/1bGK7mpQqaeCx+Bf198Xf6liFWSU4N7DHZ5WnxHflVBKRkpAP3xCB6oV5FfVVBKOlxAJCkN/pheN98c6hbfWGkR20YhvskXT3/Ri+nTPMZZZMrDu8076/HFND5MuJJImGEQBaEX45XicLIl1UsgTsHc6pMtNhBZffoosSZpjhPMKS0AzozioPN7DO7hjBIPs5ozLXeBBfNUDiLzCDZzqngE24vLeQVebLZzCqw+nk8gbtqc5DnOJje36pX5APx8OuzXJtObX9HsmECALyGbyYPKRTfqQRMxtj6BDcPOJdMzK7SMvaiEWmj7cwNlyikZxYKuF4HpaTWNFEqRzX5mWekGzI+8iibZwTUY/WmRyfJ5RJGNwPjywizJU5xZOM2ihCPPiB7p1VbkRRiUdbr4qNxXNbdY3iUNPYJRzEblAtRRzC3TIYcD5pZ6D59tF5LNSGbGUZPS52xA2tLRiGc2kVEM/pZDG6dc4MpMrlsw13qMNqFZAsI0BgnOoj6/yk3p8+pNl8NQjYph6MLQ8UwLb8R8XoaP/kwnh9IhcKhzmFssz5qBPqFZEk7uStUjrdMNzSxzl3t+RnbbPRuJZsdk0y5wZqmdLnAB6WYj+DHpuAucWSS5SQtHdbMJpl3gEpWqLXpm/24Ln7OoqeSFalaz/1+i0Afkz1zyAwyOHCkTTcqf0/2a4hfywcFIULtwr5yWqZKwGJoIYwiypy/ZUpBVJjKpRAnaz06LG72q64coA44ryLmhEm9yGyI3VhpO3gIngvWIHhSeKWIB7kAKLyd3KHCjoRhg+rYHbjSSFUZu/oSJicJg1+a5tZwX0QEB9H197uI42gzoHAH63/ZUL14c+ZOHCvgRIS5irqzl3JhaHcaRmE1iYpFdzq+3J5NXtPIjYsvZwP09TzPbhwfgPEt2FkIi9kkU4B7SjBDc9RIJhTRzQtI8JlszjQpK08nDBHLATxenbzUj6y3SNAN4qs4LtHVXTpagoGynra3gOifPD6Yt/nCP2joB6LiTezUFsPQ5CN0qpA8u1gaFc9vE2poDqaVNFthBX3hwvHf32rDwNjOdNdMPtFWm8mu9YUYgvJLIRrrQBlUkWyluAbSBjyJoXdAh6iZTFJDDTFvBhB7qxe4fdcFFnrYiiaez7HJDTW6y5kdy0o3wwHwMTZvfYbArbWB0JkE3ntZIpALFZyK0gaKh1ebsVF+xFNlIyJ7qVFu1xZGzTq0TD1U3d3OpbZya6AtS8N5bjVjbi0uNaJPXcwlgXehrWTQOeFI8T8hzcZgQIJkgSHMv0xewE9wouve0MsV3CUPh/TMsxGqjrDZAL9CIxnnvBS+cztExxrKdRJtbUzxtJVvgpcqDDLw/Ud8MKUbTMxdVI5VzH/jkrA1DfKZVOejro9PZEJXtPtxC8EJWDLxEbksTt5j0OYzCZ/VBVUNAuaWELPKkOlrTAXC1jYwcAlCMFHiZ96CVPd+1UEKAOsauDUClDcA8uGEGn7LUjHN0hRhzkq4gI86CkBPlgLWBp2cyuwGoa0DWgKz2DenE9P7QWi5pluTTl5kKAOpu4eXOdpWAVQot3zuEMvu0u0DFWnJ1uEEZjiwm2zx3GgpAIXoPIPXED3czMDVrG0TS4UwfyU6A9OTaMJo+6zXW9vXZMLSDXBmFrknr6HcrSKltYsMo2oqAwj0mINbEjECpslIKSGqU5uKjqnZNMBujaKWnzf2dTLo3LSHIeqg2QtCJ66NuEodzh/H0eD9d47PjyFfW0w8i+UWREiRwVVbfGyg6amEQp4pDgyaS0gJoEwjPX8mHjE0krovgp4Bi4PJctjUJc6+txiEoHcUf3yttMqxTStFxg2ID3F5rUQWTPtHORpLahz4Fp2r8Gk5P+NEH1MjQ9yROyYwBahg1dOA0NYgNVDq7gGss3odmDtkO8WgWZJ7wXn0pGfr0wJt69DFW2CI0gLbfu8InL6bg9LGTORcyBaePna4orgmpHoI10CSOtUyg6eNGds3pI6eyCW8ALgGhGwVahklN1HTyjkhBNH3cUp2lkeosi9SPMoVTqALIGjnTVCgaucolVxlC1BWAkkSquoL+BGdN9DP7CH0dYQSG00Wtu91CL3ARNGpAKqY9NNkPAwZeqtzikw0gfro509Zb1ogkC4AiWr2dRLFCkN0Lwo6R1vfxTh097N2iXH8yszgbZKgWZGLLlJpES5210iVbbMCoS+oiurpw74UCy3KaxIoeWtAkVmhgoElmNacs1IxpEi6510Cj9COKsH2RjXeaZNcZPmYWLLZurkmo0A5nBZleU6hwYjxdgufsfluCA+D5u4j/QKyU3PJGt7rb5w1Z9Ihrdfszixac/NUkteyNZhYrNOulSaZkJhKN0qsOYWbZ4imfNAkWGoYryBxsqQzIJbnooGNHKfAb+VLpJybaxnGJthOkXmrjy3b5T4XISq+z8Q1Jp9b27QNqQ216hSSqb+QH3qWeBKTe2dEDTBLPJb747+iVIHJzH3579e7bqx/iJPodOtm7mxvy4XdPgR+m7+inP3779u3VMcvid5b1+Ph4kno+2KUniC4aMFtfiodOIF4Cwk9+RzcOk9eyJC8+9Fzyd+6cFHJPUpjl8Uml8y35c4dGzNkxhSG21WG7OTk4Dnk9doMW3p++fUu+fQu/++4Hsu2P3MX2XYx7kaQQfPI/8b8Wfe4Hq6Phn4jVKFNkA4z7n9//x7dXCQyQoVz00R74Kawf+vBEthem6Jt/+/f641syVK8+XYVR0QAL5D42Kb5SK33ZVv32qrzC9CT1HbKCBq0TJ3HK0Sv6dUUOnTvl+8ta/d9fff/KiWIPuj97PkxfvXv1b6gckBnxzTGtkqBoXxBZYjt63cwuw79YpFUpPsrpnTPFN0RolHgHD0XF1cvkU3pQCX2w+Z7gZaiCo79eb87Pz07P3ry9eEO8oskGk2aT+TmB8Ovd59vr5oSFqPCrq9OL8zNh2Sm9Pxx5XpLZGUg7c0RiNJD8zdXFxak4iZ2fwyyKsqOK+NdvLrdXV2/fChMAcVxe26ogfoOKf3t5cXYpUQgO2RFbBhtR6ng+6kWjRIXP+duzzcX5xflWlU6GHFSpXDbbzdvt5eXFxbk4lfb9firF8xbVkDfb07cS9mjd2qdC4s3V+dvNBaokghxwCmibdn1qRXF5cXX15mJ7uRFk0NoPI18IqHU4Pd+enSmVQXmfpRKTqzPUZl6enl0pUlHhcPnm/M3p29MrCQ67jMTIas6AHOF8c/Fmqyy/zhkpXApnp+fYJyQYHECsVBlRr/nm8vT88mrzVkZ/J0t8FfEXp2/e4jsiJboLKjx1jhAHSQk+mhaRcZiSOc5RI315KVE3W913CMnVAIqeeYb6i/PzCxnPrMgAFwnIvFSt43j7ZrvdoC5MJqzJ7GOEDyy7IC4mAJXCq7Pt+dnb841EXRm7L1eF0uXm8urN2ZtzCdvQXZXyPnKFgs2z7YVwT4Znk3wIY3z8Qi3AOj3bnJ2jJlQi6KaL4Up1BEWab8+vzt5IGL+UT6dSVPow1Ipt35yfn8qwKBJWaQjuUO18izi8lWjIOyQSeFBuvE7fvnnzBnXuSpEmvWlZqcHYojgPDYq4eZSzEe9/+fDr3e3r20/v/3ISuDJt5tX29PIcjYZFJTfbbzr9J9x1oL7j7ZlAjDkoWzKee/vm4uzsnLvXKkV/vftgX5fThalcOHG2OUfxBH+P2VAbPuCs6mQlodqoIWj27dnbzdu35zIl7nWaQ5t+JUfk4ur0AtU/CTP0eJCU8+TsiRKjzZu3F5vN2zf8kV6TExl4qdsFjcC359vtmzPudrpLos74oV5Im7PtG+QvV+fcA+GSje+F9zDZez488WVapjdXaAx+einup1hX9F2MI0o8eyvTL6CG6Qo3jT3ZrPlKL0CdkoW32pHDp4fTkzg8yMi+vDrf4GaxH6vwit7Iij67RA3T5vS0XyN5RW8lRV9cotH1FVJbWvKZtL3PLlBoePFG3t7nkqIvLzaX5+dvBoYrLMkgjiW72rfby7co/HvLryWWJdV8oTDm7Ozt1UAbyhJVmFIuftmcXpyevT29FNCsiJnkxF1dnG/fnp72I5YRM9r7BEI8BSNVdpuzs1MUuV9c8isouAwrTgnPPmzQkJ+/uuK1C0lZby62by8vhbsfYgF3J1dfLrZX56ghFg5NSqGSXe3m7cXFBjmYRGBIFv4h6vqzDBWvRxIXOFDO5d5eXpxdnF5uuMfrHDxkLHKF2pGzqzOZqaU2jV1mn26Uxs6bNxuc8fWtxBRgm4rSPMrby3O8UCQzXmoPHKRq4vnl6Zvzswv+QWrPBj50yX+ul17/qlQe26vTt5uLt2+Fm4Wx5XtxB31z/ubq8morUyDVnhPbARnwIzlDIDMgr9xIjSUbhaLWXrx+i7rg7eaMf9VwioXceBL1SqdXlzJTSx3/VHNONHxAXnGGDHJFNkDcfrz58unj9ce7v9q3d7/99PGz/eXr5y8fvt59/HD76t0rxLW7SYPI+A+83SIFD9C9zSLn/p/xZVd4LQ1//A7/gx/A//cqBkn2OQ7LP9+Vv8B9crbFeOB0c7q/2Gy94Gxbfvl9+UuxP+PWvf8UOSQ46OGwNpWV3/9n8Q+2yU/FyucLVeA/UWmhsvk/H67v7NvPv329JgX0w5+fAv87Wto/fnu1OTn99uo7GDoRPlaFPvjt7ufXb769+vOfviXfwnLTD93s85R6P7a2+TyenUTJwdqenm6s/3vz6dY5wgC8Ll0fAaM33qXk01IfBBDmvv8dc7PQbZa7XkT3Cr36jg5+n2+RZeCPld/jPT4J2eGzj3wXJt+FIMBf08pYfd17oG4zG8/gp9DYvnqm25h+lydYc/zMO+v6nfUbikZT68ELjw/WbVUeBXPr4dJ+jJL7NAYOtLq1weJpu62avFWwb2jT4NkICw0wbKBb4/KPRuUfmfK7E8YGSHRFMJh0J5ANMOmK4GFipmC6IhhM+rPLBrj0hbDtMhilmLHPoCg2s95MuBlWPTG8jIx5dE8Mk9HYdL0RbmMC+VkOTubPw3dQ9Ajz4Sl/Q1yHhU2wY68FGGTJFsquPSMTGGbq0YhAcZbG2p8RgZMseyM7oxR70gT5mTZhTxqDX2fdygCnjgRWpNhZxjIRLnZElEw6IXRnOFDUavZwodyZzxoqjGzm16ijw3uAgHfkMLj3XD/hQTEcgatRUgxBI3Hj9DZ5Iyw55PKS7mymn4FuRyKDaP8Uin5qfRlsq7GPpRgxGVscmyLraIIRgixhbHqsQwtG6LGEMegxzjPop8YQxKA1eMhBP6lBMVwFOXDywXRxDogcqbWsHZ1mKi1LGqct5zQiV6/bO9Nhps/tieGlRI95zMCKShoh1jn9YYZTR8iYnTrHQQzZqCNlktDoERGTHEcFcwae/ZMk5mPQvkzu1q63dXyORq8nlMe2gwdjDNt2UOZow8M+OmOqAWJL5OpRxo7WmO5hxmTzkO8fNzDMuC9wbL0gMT9oassYmWYaOjxkhNKgpJHmqHeoyEwD1BMzTal3zsgos5403pnX7o4uM6U6KpKX6qwkBegNbnYxSXFQIDfN7p6xOZh2ZfLNj5L94a3p0YZivRMCGvVgnEFgmLh3YMAgkw0nk61xJltOJmfGmZxxMjk3zuS8zWTcu5l7qZjrAUUjn3YWBFqPlJnIWs/0nvqJAHWe6T116yF6UfgJ7NLeo72HP/z89Wx78wvectd7tI9M8kENPtltvvD8ZB7b1Qa2qdU3uqELtUGZRRapfD/F7RIIrdgiJj+7uLo6B1cX2zfbtw76kFq1TuJWWMdqqG9V2lkFdWuQl8Whz3OawWB96gzQGtKmt7DDLOKPxfWtPGU8uDlxqmcybRjK32KS4yjs6l0bOEG8Oo0qVmKqTK8wL6BJdyGaQ5FdvnfWp0nJSlCVBARr1IXSElUmW2XBUFpCyjhBvj5VKCkhRbDMcB+tT5kGMTGFAoDeTZ3Ei7Noct/jAnr1+ImpFxf3vK5MKcpKSBW4xjoEJerQPk2cFdagipaQMofYSVbYTFe0BJXxVlgwJSthVew4SrJ16lNRE1LquF9lzaloCSrztEpdnsRV8bYrbAIoKTFFgLtGTSgrMVUc4BzhCpWpeAmp46NAaH3KlKyEVXnagRUGm01mUio1bwFbp2pNhmIqQrIeuULNamJiCq2zM/WlOlN/lZ2pL9OZ+g8Hd4WqUFZCqgTpCntTSkpIkThZYZNGSYkqUtxf5K9ToSY5IcWSzFmhr5WshFRJYeN2uHXp06ImptQaZ29Sidmb9Dl19pM7JhbQpeIlpM5Kgxq5kCZfaUyTywU1eQrWOH9T0RJS5tGdTnYwvy4lKx5VArq9bjVaNAnJbDpYiR5DvIR2HTC+GPx44MP+MdX+udXB3TU4xUYQhTaI49HdOOj78Y04Bc7URhy8eXh6B0593pWxBafhEfWz+n1hyEj4MK5V/G1hbRqHc602l8Hy72xoXBP7Hp2+Agt7qfp2MT4v9UJn0Ek7ZZdFgWcgYO8oXbdE9G964XUtfqCcuucxPPP+xeJJZU+TdCIX2o6P/M/be051R/sipBlcJpXw1qQFk8x0WcAwN7ALh9P4pfBpmjM1ncwqONZU9rwbv7mgQ5fiuajGHkcGLZNkKwLTdJGjp8v5QCWdg2gGstzAnBUv00p8lyqrW+/s8k64esWiTmjfDDylJL1qvBbPUR7PqYMFL0a2SYDXzxfjWkrnch4dwV9xfjtOoixyIn809ht6hiuqGzyYrr+GtlWxql/KEKmU2rNtN7pYhJ/HIshTyv1izT2c4WqspPB91BMhuhMlGXx6HZydTQ8nC+2yBDAOanQeT6APQcq139/3dg1w1MLmuxNguHCI/SxkIqu2gdVgYVH+FoOcjmkJ3hrIKLogAGHXBaQKg1UcVMQyZVF9S1n0C6RBjzHnNXI4hfvcSpH52aSRE7i4hZMBfy+JGbStO3zsTKN16bTosvYtSPQtXJMzaGOS1NakiYmAhS1MOPQNXFEzaF+Zfq7kvbDVevZq8lp03r1vZZwWqc5Kohyi0mDM7uAajwk78tqh4RAb8VBxckDQSPUzNR3cH6wO2JFOjLtwlx+KtRv9w6suaTqeYou3hNyr7zETehpwlK6GtWt0BYvphmr3eHUZGkpwDSbEhhMDAwrGOsJwCyDcOdHJOv1tbLekkDTWeII+0Wppa176uqW5l5RqG/iQpIxSbUWygeRYBlsRyrpuRhjyrUnaTi9f2ry0B+VP03af0d+eQ64zdHfLUGdymKbvbx0QL8O6K3qabAwek8Xdm02CQwGYeJGLSmpxJUaJTCuSPofOMsw7kqepAseBMfI2L80Wag8HCUwTh08ZTELg27soxNd4LdW6jPKYVqOTB3Fm8gPSRylXqWOXYMwQPkkYyXTuSaLGebm25XK4gkOnEoo00HO7Ql+6/sFNWcXxoSgDa6t9BavRTU8yR9MomrpVM+GJNK78keLsdh7L7CsWKc5LnclBMFKcl3VXtHSkOC9tNgmlSHFmJUaJiEWK8zLvSJaKFGduDwcJqESK8/If5TGtBm2UUP81M++2YPGQdl62A9KFQ9rZGDOEc4a0c3vxkORJqj7vVQ16efrDdzcwSJrZpzNCb3iHziAxssESucbO873seXaaffEcXcWc5vRE7NkYky1QbUq5kzSz59hETosxhpVI8YHqzA18X/qkPend7/NatCFUbCS9xKY74qAGNtyVoY7J9bHS9IzFMaJaa22sSYrjHCN+hcpYlRoNTkb2CWIBZMeAAb8ooe3iYk/fM7O7h9O4JZuueQcp8ntM43WkBmoPVq1hTVFQw5VqZaxeNAaiZmpGMYZpDHcN7VXms3KDyFDzM0jUWHtUnN02Y/YCe1FvLih0zVwTM2LXxoxtmu/w7crhwaBjD4lb1sOHGA26+ih1Q2XD2BeuqyyMbAvnNXtnQ3iXlRGLHgHXwQdJgyJ03JF6MN0uZlfEYdCsHW5mrOsYihYLDZzlgg0ke9iqjrlIw2RvR8gv3OUNd3cdZuvaIt4fDvXnG06eyFOmTYoD36a80VkGoa2WiEiWRL4PE6UNl+UNtTPsvagZ1zswWrKn5oiqh8mt9D7MDJw05mfcIqF5H8acs/INJSXn5otrmJHYHXDuTc+JDtHtE+Ci7HvhvQ+eTSRm4KPcIiBGeY7tOdO8+bbqlK/FqHRwfVmIdUP8EpO9T4fBG/AEgoRuiFC7j9ngoGHROkTA6jSjghaZVWW66ozOpPJcuYn30OlpBx0FXxA7XcjDmT8G6g3BM5qiAg3vqgQVhZJWIbXq8SoOPPnXiDi4CuI9KtxOydFfj5aXyYQ0bLXLxq7iIF5eixLvUVFrRPpNdOxF+qomuYBnZv/GMkvvLuWbd2ozFyBxaEr9gn3VkZI7+NB1kwd9DoHw5vaHQoXSIygBgVq/OOU2D/OujAXN7MlUYerLlIBgGS1Kuc1De2DXr28w4bmB2vEj594OQAgOA3GZdC1uwRqaFGFYnyputSiUNWWYF4cfeQOv4lnm2ZxqTK0xcjx1ZPhtOzWQdkBPoTXoCeu3Qp0kfXCt7ifteet1ujF/0927DrRRy5Zymf10kJd4/VufMpx6eCtUZICT5gC/yKmlP0SguIT+7FW+rVRZ57uUeHybvoMvK1yVEpSQgAqzDsW5dGAPzplK4FNq8REmqAtalSptXuY7kZYrz91QdSxBm9wuJcHatSolRu4mHatdq9Jh7O5rhhJGLiNW0WHkIuLpBmJVmrR5SSlk6iyNHrVYx25EWj9U7URaP/T4EuOJjkEQC2uIk4IZirugREzRKAc8liFZ/fDS4+LGodda8THVHNp6YQaTJI8z/uiW3f+2t071FkIHy8cJUi+1Q6S3/eAlWb5Ao9SzAanAAOfZHyQntEWt7449cStRmEVNvpJyjoO8VZqknNjhtAlHOdvFXshg9gaHpdw4Rc0tTQCDKHnWP4hu485u27b40rB9Ujwe036rSlCTQCzMUP4tDeqxiHLNJ3WgaB7TVag5Qk6iNBOYgeQA518F4irCJjuJcpu9veYqMN6WumOLOIr8VTniBEFJFderm3QNO6y2iay5mZ/4WlfVpKGllppJrbhGjRrcZPo91P7CsEyjh7fIrkNJPp7yLh0nEdZuKBzkDgjZxi3RyaFNs3fJcVi0ZNPtrPoshQeYXM3EtJ2W9rnKQh3na/Izdj6sP2CJc42jlDhfYh4Oia06pIrBDD1QnM/vS0jVsmUuxGsewMbRI6qkGsavnSPfo9dVtO3aorBUiNoiQbyrvD6FTZAjx0jvbRicr1g3yo5LMW/QLqhZ89Bg2UBGLXklp5mq9U2pD2Fs+1EUy3j8CtyhVqDnErJ+XlzBs2rVao4yCi60p01Mw/HtlJNVej11uaXkCE0jKQx4A4R2xVnWaDRo6FHiGZ8O1ZL1aTN8yxefZ69CnQFOmoM7HDUCT+nAZfvwbRYNL0537I2FLjc1TLUm7QZmbPXoKK51ErxFzj40VesS4Zp5wi/cwySE80+UDnGvqfBNLzXembsGt+n3uHBbnxxzKKYAVlEEHT785dB8cRWF0SE0w4RAVf2W0r+cGmgSEW0H1sBdsR6tQQVZ7+PtyVH8m3mBzj0GNeYCDVEpujrq2iLDdQC0eoMMc5LMcValR4uVhEJxEqG316dSzUtCqV2+Sp0qWhIqra8GtWlx9ejtlxdoUDvaDDEy36E3GqEFLVAeLG+RESzF5fl32WjuEHMX+uBZX2dY4M1ejQuxZRWuSfC0Q8XTNkiCh8vAPqCO5nYF7Dt8zFdaarS5HZ7qTitrTcJ8BggYDCVm4V2Bk7EydCJ3vllgol+5eoPtW4nX3IaEDwHHxSJcFsJQONkfyP35RoOFobBoYqYuh8k2BL+wJFlukvYBhjDx5jujNmTZBgc+0g5wjnPXmjbligEf4TkjvyG6vPklyoftvQ/S49KUaxZ8xGc9uTvEmfucLnk62v0OnWXbtJoCH+UYHJatdyUBPrpZApxl+VYM+AjnmefPdxx1iHDFwPAxrmaXWm4bwYlcZxzwN9THcfY4I74uf0Hq3CRp37WklSsGoh3SkqRbLAQ6pCU5c6dlafYGSxKuKQh0SEsSLgmItO9L8q0YyLfvRXp+zibe1EUC0yoXkq0OizkmEXxvNzWJMNxHtqcGgpnn9Alx4ilN0QMG67B0gnwZjlTwNEO4FEPIy3DWTFItiiPpnDscg3QhX6SCpxnGyZyNa4MhFTzNcNa11BZF9npplyO9XGkRlrXsaZ7zLg+2aDKXAHmzqPC3/vP1nFg/MincEM3X+i/CkQrmYmgX99QvRrQhf4IvXt5bzKpt4dOWBSnis5BVa9nTPHf5nJMqrXrEmkvp+mhx9GkZ/6xkc/RfINjn4UKtUkP4NNMHxGbOw98tpg3hPGWfzDlJ2Sr5hLX6N8BxgbWiDtfxlaKhqH8RqpC3/Zw1w2WL4sjVJgNR/yIUqWAuhov27235fKOURYhSwZyjlGWaeCqZa5Ti7OecWGqwrGVzj6aW4kll8/Jcto3vc+AdBS5Cl7kDT3rukLG3qDvDmCRhZKN/I3zi2h1Mayq1GamLO5tZ6ZakHoHC0kO0dJ8CmJ6PxVcg4Bhk7qyM5WF7eslGh4KxCQgqa24XKC+bYESm0jWrzpE7Vbv4bFPsbZ+vhtT8SxM1GEzOKZCHZ402h/lyhp306Zm7+GHK3H19/fyc/T2TNF/H33p+9s5/jPxYFKCzTa/ccq72vKE0bdObFIRqxrKUaxJCNWNx0owFBmMXQhdZwQdCO6n7oPlCRM54hjCL0q2x3FBN3ZkhzQALo2FNV5725m5U6zLCGWAxr0uO+eJ1lHQvwuw88TF0/Nwdui2zYe3KELFnJF8gwbcwWYvysfoie1btMzQ2WcwkODJD3OKX/YE3r6Bo38Dk1gC5tjgOyx1MzBQxrXYYnh1q8yIjpODMwAGMIV5NaaO8cEJFfILrzSy8WtIs4QakV92/3n2+3WprEVCzZ8oKhGjHbai40eKJUjvzTJwfGKLVEDZZNj0730Z5MnhNcVsbHOl4JvafNhUquFhtceLuNtVf7RMIeymSOs8UmS7GXdTjcVGQRYGJQVCphFUwtSgZq5Y33q4lUZ55oYEZGRaxpsRRai6ME+iADLp4Az3O14G6NgNzIyyibPmjtOEDDDP7gLSMZyTblTpK8WcEgmvafPSaEkep+V5qICZh0SqljXexME3BAdq7fL83EW6yyPXlTkYCcRJlkaHb55g0e3InaeIxPhJoh3mwgybWLce4DgifJPyYgDienWlT6ijFOEoysPNnbMSbEsepJdHvqPWc0XJNiaPU/pbDfEaTVeJGSaUwiI8zNjK1vHFaGSCXW6POe8ai7EodpXiLH76ZmWFH6IQNEwiC2buRntjxmQGQGhitsLiV0sYp4QXxGcu0lic+iirbxamZ1BsY3IBw6LhTS/UjBLFt4ABoV/WStkV5WbVguTnTX66vp7cPvP96Y1/fnJ3Zv979K0862zAK7RQ6eW8ScdB2WKcZLYc0tpoKWTVbq6TCkdSb4KUG1jOkiVM2HNybMYv9sLXXoweDGWd5kA7IfPvDXSIVHwF/Wg97ykbE9qZWVNRKYGyHO7OdVNxRdOv5HlLpE9Jzun2lG3qmt2jhKTbTl1wwbd1QyaKMrWFCRk7ZDs2FGVe+KcliE2pN6hgn1ZU2QozMmxgnVEoZIVIMqowzqcSMUGnH2cYp9cSNUMNh9gwOVIkZo1IE1+a5VHKaZKZXpPpr2FIrJfUKkTlNixUTulbSEig+buFaZSslm1lo6+hVLmp1hY4OFauHA3KD6+wcK7H6F6t2fg6zKMqOtg/twHNdHz6CzkiIZ1NP55kDyDKb5si0XUh+eCHeWUJu0LajB5gk3pRnpL7NC6S/UBiWKXfG8BKzBJXQX8QkwPSyZzvYQTfzR9cl+bZ1lYiTG7vITc5xFKIIgCNHr18ytNM8xoEc3x2DzAQvPW/yKgHAcaAPk+I6d+2u07V4M21s8Y3VNI3V17xMCDPGmWOo03w9CkIvxrfYhwZWwsxo3KHMqXCcghdVvkN8hYZ+nBsqB4xV0tIfTmgwUXk9TU2RywGIPZ3kOc4MbJPWp1abpYBrr161Lk01X+a+8blylDVW9/KKmJoiR4kDiBp9E4mkNSnU4MehjeMEq9amwY9HmwA461anQZCndYF0SixYa3xAqlCXJY9mR7BZdUk1CfLps724XLtGDYp8Ol1stmvXqUGRQ6fDytu7g1B7B53fY3APV61RhyOHVtkxgcD1wsOq9eqxFI6D16pZjyW/Zg/Az03sR9SrWc1SPMJfr2pdmjoWKoemg7AUN/EeBq87lB/1FvSzJDRwKFXCxrWWrQFUyU/AcQoUQ3cS69OsQ1NcQVMHQLWryD4jylASBbj0sJ3twhiGLgwdD65jfmZA1RG6/C25l6W2mQsJdCjZo8hfktQJdrnnZ+R22+c1FySDrbC66MXmIG31Cvf5SqmMOiLvoZi/fREqt/kKqwxQRLp+RUuWwuoFwEDma93aUZLCyqXeIQRZnhjY4aJbxRZVYUUdklNj/VrWPPlVzBIQpjFI8Oaql6LuKGcl1Y9GLtwxqfhx5HIebrVX3gqPMFZSe92tM5uwnNIvJroYJ82vfBSDv+UvpCse5Cqs6ospYiZf2dJdfZ/Foiur8Mqb7GGy5pbw27vPUsB4sGNZL8xgEgIfNTl5ijMppFmUGLnuU82weLoU/WmN8R12pAFXemlKT3HmUpxk0l2rhhU5RmPAriFc85sr1JpJVHF+c6WqjtAVn7XeQzKSXa2yDKpyU0Mr1bHPUnZSYfUK1jxV5zNXr2qfr+qs9YtQWXwrVG/6cPV6UpLC0Ta+e8lQYi9tKg5RFVbUUFom3UoyszixFWxOJ7yE4mTylVN57QU7yNXQThCPbjbRug2EYtomTlOKW7lUsUo03SQ30xZ6b0Vbjyp7lC4nuEnMa1hwverYw6dPNVWbIoGeE/kmqo/XRbcT4HoRWMtulTa5enfOCGlOxypfWd02B4bKDL68I9g26hoqE2/hCjQWQzZas6YMvsZSxpg4iGyn/ZQHXDmQOw8NnWvuFTKYI5iiGlU538pyBhwZTEHigQUZUumjFHfeIcwNJH3iJVnLH6fpR879bPM0TLIdFuOUc893SU6ABQm3OIyn90Y/fH9Jf20yGKfqLOiwVPg4wSNA/9ueLsiywYCDahz5z0uTLTlM0IW4BpKT9ksSbrMYp7xwo8XZXDmzzB0ySTImBTs3q2CD28D9PU8z24cH4DzPFsIymY+TEldon0QBnp9ZmUpNWgJK4Ykm8moBsxalBmgJKpXmOEUozFao2AA1AeXS1EA6LDllKBUB8k8Xp2/Xwr7kwkN/DfWdp3JDx12SaSV+giQ5NLwkzYrABNF4SZLxJMHDkpH2gSPSLiGWjgj7PMZpz7Cbgkl1cI9Eh97FkvwuJglWV67i5J3LUe3R4COdZ96CXWyPxsSFMf7z5ux0QX9oMpi4QAbvFoEk8Vq64Mxgn8co7cSLYeBuLhecLWhRGL+Z5Ag2y/EspU9R3F5cLkqSyp+iaeCGUAGS0zeGFvlxFiVJ5Y/Psqfhgj5ZSp+k+IjQFuyrWhTGJ65BCi/PF5y0ruRPjJyCGGSvtydPS46cmhymBnpIMt5Ys2jI0qMxTjpLbDfZLTnV2mAwStWFu3xBnpX4CZILxiUux4qle1xwwEeFT01AHBedfzhOUwyzJIoXnBFsEBgnOs9BHCZN1lGbFsnjvbtfjmMpfZwizsu5bDPZojBK1g8WbIKo8PHJBxhEyTO9rsRGsqMF16UYZEYVCGGG4Jx7mC1o6Q6JccJemtn3jwuSrQmMEo28BefNqPDxKQi4YPdJhY8TvF+Q3z0HPSddcsRZy5+kueSMWCl+kuTVsiSvuOdEl58OnaaagqVnbhsMxqcUl1yjSzhW6BZdY+ZZVU7xpl3gHBccqbcoTJMlu3zS3MuWHGIOMZmmHkX33tKGrjhM0sU3TsIZdpKP0a05jNKtskwvx7ZFYZysFyzLtJI/SpMmD1iOZ4PAKNFlt8JwbX7BD9lOsmBf0GTAQ3XBet9kwEE1XXBmp8mgTZXnhsmhlEHtWemFtnzi/DC8OzuLk2h0JxjI0e8wxJcYLzCArWmz+AioQveKzZvpZVojBi1xxXAShhh4yVxntblV6xMTVy59DqPweYkJQKZaTUqrPU6D2YscpSkULdNuk8N/6TKBecPuw3REFIkTFCJl3sNKFGnTEVFk7mQ4HMpM57sZUqhYf15UgZoCH+Fl9mm2CPMd2ymenjl92wjvyfxso/TDDD5l6VraonFaMoqtqEpPU5NRcCWN7zgtHsXQa8kC05MNHSoGPHSXOt7T4Mt7jKd4erkp9QZl7ln1MmdKmR1sUdYtFly0vT8Wro8VAy66WZI7y4YLNQUewssPwoRGW3NdYDfCl3U7HU+yj95MjO/tEpA891J1MLc1Gk+ZU2pOmVk98RabatUmzc6yKZmDYLHItxjLSvwY1XIpcn6WDckjBOt1h9kZtkSPUAS+dwjnyUrUpdgSPUKx2Ipdpfyen+gAgTG6JJkMCk6TGZcTK6pt4dM0F7Rqn8A03SCace66w5TK5iJpJ2DGrWx9oqV8brKoHB5AisLOpVm3iIzRb6RBWtKLWTTGqId2kC/BtZI7Qo6mlVlmpqyKqIZJjNEuS2ApLx4gME33MQEzHr7vUC2Fj9GcecaxjqiH5xfZUb+NxSxBdIgDP+nF2i02jzHy2YxTIxXTbGgJv0mLHHta0JZ9+SNkoRPXt9cAf4G4e4jBJOGlmtWu9DGixYkjO478BZygK32EqB9Ec57KKBlWYkeoBe68WYBKbrXccXLLdJgNwWP04nT2JbqKYUv2BMmZj9w1OTKO2/Uo4smLOefhmxxr2RMkswQ4CzSJLdFj02PAxYOT+Qk2BI/Ru1+wy+4IH6e5TKPTEDxKb+aUDjU9RiKHwSnaJYt6iMII5QQ9j6Ii+wh9nMFwfsIDBCboLmfcrvQRot1jGQuyHqUypYLvLTJb3pY9QbIYkSzmwYMUJigHXjrjEesm01LyBEH09uZswZHQMAcu0vfweSEvaMsfIUt26y/XIvTET/Rp5dRkUSEXWX/sUeBbk1p+or/HYnKedIElfcZ93MxJ3IUYVsK5/HVJR+UmOdNN5iNVavh2cmYbsJCLDlLgo0z3T2Lfwb2zHeItUSDznEW1GGXFp1jqR9mst2eNqDPAhVMJepX5ouRrDnykcSLnJQlT+Xxk93v3uCjbkgAf3SNIl6VbEuCji2/RWJItlc9HlqRIX5JtSYCPLs5rsSRbKp+zIVu4DROw6zx3y0/FHPzjjpmv82HHHPyUF9kPN0CAn+5iqzlsHlLx3aIKDHBRDVJXpE6bFX+otKQKg3dujIZKS7ItCQiESkvSLQnw0V1uLoZBgpP2EtsX+vL5w9ElyQ5eKjcaji7JdvjKIGY4CkI3Chbae8fmwR9LL0p6csNLO5hdkmsq4BTdiY9Fefe5iE3CLEq+5tAkLXw/dgI83x46Rtd5rggzxw7apb6NwfRbpUmR7v61GsLGVrmKp+xgb+Cw8QitUiAHNZAiElmx9wnF8kby748xHZbPQdzQydcxroyjroP09hBkeTI3w6bUsX0Zs9UTjkoybw3hrB6L1g25ijF3reCuEgvUh9HKMH2sO06iLHIiv9fdtJ7a+XA8DV9ZK9GDhtUuCVtIlNURO54IeQF+bHI8yQ89COGb0+3m4pzP+PXzc+lYS7SGSUyXyKKkJxnzFNNjsMtTvhIij86lJxFm9URPF8kCLMco8pTBH4/ggbOJIo/OpR0RZvVET5fBAizHKPKUQeq58BH493zFUD49l46lPGuIwHR5LEZ3gqtULhfn6MXjHT7cJ2fbgYLsP/R02D71HmSUOZZrpzF0vL2J9YN2eIRkWYShVfG0mES6DjDkAouz56M+XFVl3ASnBj7A/kxEPy8Q4pVAH4J0og0uHy512tgHxylfPQFGTUq1sTqErUlOGipc7OcHb8KQpW+SQxJFJk0PhY52PJEBm/2e6baKKGWx5Y98JdnDNPFigFMS0Az4nPHXwIv690ZMGqlNYOy7/s6JCcUynMd7hTrVvITUaZpifmcWKKepGKJnjxkmL2SKiTHHIVE3ixLnDSE2vCFECe/uAjuOHpEiMMu88GAHII7xTyLXPkXfL2PeQu+q1970HuBkPhGRCKJuXq5BNmYssn25FtmasQgOkILIRS6IbP6S7cNQxKC1/j5MZdZOfyc+NeZRg/0kX8S2pFHYlFTDAGxPuu6Pc3J5mUiY3nt5ibC2R2Lqe8EYt//+Ap4grqQG38g8EWfIvCVKP/N6HwiWL3phgQId4q1eZMketQ7ZUaDY6BsLFB2VPPihWBGWL81fjKM6SM0ET21RqnZFpbCs72M7lcos0RMTWxR0aiyYFnNEUQjDfj8xgDrIkPV04gw+1i/4GtfgqZlaSJVpu/rSatrBajyJdLB6BPvB2rhSpjN169GMkdWbQz3jx4A1Kcg6K8yhIk1xt34dG0SFlTR82FKThsMnMjnU69wDtHpF+3ylVD6C0PXNJuLXqHCTrbC6qXcIyaas9evaoiqsKMgySM5evQQ/7pDlUtZrAgQoENtFT+vUlMV0SE3GXEWhf3sbWigRO5nbsC9lH6SD1SMo7Oou3Huh0Ut99CjXJCqspOl7ljSpyLyMaVJBEluuXr+SpXgTZW7/sQ4dmVSFy7FKnm04r5qmAu3RFS/ZGRKz6SpZdhI3jpKl906YvvVCU8F22Yqr+1IUVVDRdKYMXSoy0mlwqFiOdlevY4Oo3LB89RoOn/7nUG+2m4M1KTp9nTCXytVA90Uo3GSrMCxfva4tqkrD8tWr2iErPyxfpaYspkLDcvYX3VUUz44RMTtKQfdU3/ALvEsjDVzbCVIvtZMsSrfrmAppsqtmQ5h8Z5oQaTBYh2e2rFQ6Z4sjZ9UbtuwL0LHLV0cdlD5x0fmg+2fT6CCeTOx5iy3oOcgit1nuepH1cGk/Rsl9GgMHWrsEjbWPKQyxKfEGKIposaRNFKaEtCNDGr7pJYAngatVYgN1UOr7Xz78enerW2oDlWVZe59AiB1Qf4G2oAflo7pyQL0tqlDJg+dAFD2SH16IqxTpgO3oASaJ504uXAjSE5Q8yB51npOLDIK0SshKXjHKzRNCqRT8E9yD3M+QZNSCQb/1yS4CiXtNT7d4PhL8I0niQpu7E/L9SYiap3enJ+j/0SsxSLLuG4GTn4AkOCFbFE8wt+JX/Bs43ZzuLzZbL8Cn8r7Losh3joj4iNQ0PdkniDxW/SROot+hk52Q5IthdIfev8bvV4RS934My70/Qc21g/710O/vtqfbi5PN9uTsxN6cbc6urt5cbq4uLs/evrm6uGpu5f8BPpFb6d0vyOh/8gLUgNN6aXvB4fQkDg8/WK1n+N7cSL+5lX7zTPrNc+43q9aD6+m08nQblcr/v3h4rOgn5ZSmAtNISUZ8Tmp8Rn5xCbBsAK8ISyrRqwAycZmeklqcXJRZAEr4djb6yDxYBYWSOcCiNvrQxAXmKdUCAHNn3ZA==END_SIMPLICITY_STUDIO_METADATA