####################################################################
# Automatically-generated file. Do not edit!                       #
####################################################################

set(SDK_PATH "C:/Users/vinhv/.silabs/slt/installs/conan/p/simpl35774a752829c/p")
set(COPIED_SDK_PATH "simplicity_sdk_2025.12.3")
set(PKG_PATH "C:/Users/vinhv/.silabs/slt/installs")

add_library(slc OBJECT
    "${SDK_PATH}/bluetooth_common/src/sli_bgcommon_debug_efr32.c"
    "${SDK_PATH}/bluetooth_le_controller/src/sl_btctrl_init.c"
    "${SDK_PATH}/bluetooth_le_controller/src/sl_btctrl_init_tasklets.c"
    "${SDK_PATH}/bluetooth_le_host/src/sl_bt_rtos_adaptation.c"
    "${SDK_PATH}/bluetooth_le_host/src/sl_bt_stack_init.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_accept_list_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_advertiser_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_connection_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_dynamic_gattdb_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_external_bondingdb_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_hci_event_table.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_host_adaptation.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_l2cap_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_pawr_advertiser_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_periodic_advertiser_config.c"
    "${SDK_PATH}/bluetooth_le_host/src/sli_bt_sync_config.c"
    "${SDK_PATH}/cmsis/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/cmsis_common/platform/common/src/sl_cmsis_os2_common.c"
    "${SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32MG21/Source/startup_efr32mg21.c"
    "${SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32MG21/Source/system_efr32mg21.c"
    "${SDK_PATH}/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/freertos/kernel/croutine.c"
    "${SDK_PATH}/freertos/kernel/event_groups.c"
    "${SDK_PATH}/freertos/kernel/list.c"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/mpu_wrappers_v2_asm.c"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c"
    "${SDK_PATH}/freertos/kernel/portable/MemMang/heap_3.c"
    "${SDK_PATH}/freertos/kernel/portable/SiliconLabs/cortexm/tick_power_manager.c"
    "${SDK_PATH}/freertos/kernel/queue.c"
    "${SDK_PATH}/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/freertos/kernel/tasks.c"
    "${SDK_PATH}/freertos/kernel/timers.c"
    "${SDK_PATH}/platform_common/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform_common/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform_common/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform_core/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform_core/platform/driver/button/src/sl_button.c"
    "${SDK_PATH}/platform_core/platform/driver/button/src/sl_simple_button.c"
    "${SDK_PATH}/platform_core/platform/driver/gpio/src/sl_gpio.c"
    "${SDK_PATH}/platform_core/platform/driver/leddrv/src/sl_led.c"
    "${SDK_PATH}/platform_core/platform/driver/leddrv/src/sl_simple_led.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_cache.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_object.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_page.c"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_utils.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_burtc.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_cmu.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_emu.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_gpio.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_msc.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_prs.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_rtcc.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_system.c"
    "${SDK_PATH}/platform_core/platform/emlib/src/em_timer.c"
    "${SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_gpio.c"
    "${SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_syscfg.c"
    "${SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_system.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_init.c"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_init_hal_s2.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg21.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/dma/sl_device_dma_s2.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_clock.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_dma.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_gpio.c"
    "${SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_peripheral.c"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/profiler/src/sli_memory_profiler_stubs.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_pool_common.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "${SDK_PATH}/platform_core/platform/service/mpu/src/sl_mpu_s2.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/common/sl_power_manager_common.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/common/sl_power_manager_em4.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager_debug.c"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/rtos/main_retarget.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_init.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_init_memory.c"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_kernel.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "${SDK_PATH}/platform_core/platform/service/udelay/src/sl_udelay.c"
    "${SDK_PATH}/platform_core/platform/service/udelay/src/sl_udelay_armv6m_gcc.S"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions/sl_rail_util_pa_conversions.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions/sl_rail_util_pa_tables.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pti/sl_rail_util_pti.c"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_rf_path/sl_rail_util_rf_path.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src/sli_protocol_crypto_radioaes.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src/sli_radioaes_management.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_aead.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_builtin_keys.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_cipher.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_derivation.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_management.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_mac.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_signature.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_aead.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_cipher.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_mac.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_key_derivation.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_aead.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_cipher.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_hash.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_mac.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_key_derivation.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sli_crypto/src/sl_crypto_s2.c"
    "${SDK_PATH}/security_mbedtls_source/library/cipher.c"
    "${SDK_PATH}/security_mbedtls_source/library/cipher_wrap.c"
    "${SDK_PATH}/security_mbedtls_source/library/constant_time.c"
    "${SDK_PATH}/security_mbedtls_source/library/platform.c"
    "${SDK_PATH}/security_mbedtls_source/library/platform_util.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_aead.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_cipher.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_client.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_driver_wrappers_no_static.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_ecp.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_ffdh.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_hash.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_mac.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_pake.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_rsa.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_se.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_slot_management.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_crypto_storage.c"
    "${SDK_PATH}/security_mbedtls_source/library/psa_util.c"
    "${SDK_PATH}/security_mbedtls_source/library/threading.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/sli_psec_osal/src/sli_psec_osal_cmsis_rtos2.c"
    "../app.c"
    "../app_freertos.c"
    "../autogen/gatt_db.c"
    "../autogen/sl_bluetooth.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_simple_button_instances.c"
    "../autogen/sl_simple_led_instances.c"
    "../main.c"
    "../sl_gatt_service_device_information_override.c"
)

target_include_directories(slc PUBLIC
   "../autogen"
   "../config"
   "../config/btconf"
   "../."
    "${SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32MG21/Include"
    "${SDK_PATH}/platform_common_apps/app/common/util/app_assert"
    "${SDK_PATH}/platform_common/platform/common/inc"
    "${SDK_PATH}/bgapi_protocol/protocol/inc"
    "${SDK_PATH}/bgapi_protocol/rtos_adaptation/inc"
    "${SDK_PATH}/bluetooth_common/inc"
    "${SDK_PATH}/bluetooth_le_host/inc"
    "${SDK_PATH}/bluetooth_le_controller/inc"
    "${SDK_PATH}/platform_core/platform/driver/button/inc"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/clock_manager/src"
    "${SDK_PATH}/cmsis_common/platform/common/inc"
    "${SDK_PATH}/cmsis/Core/Include"
    "${SDK_PATH}/cmsis/RTOS2/Include"
    "${SDK_PATH}/platform_core/platform/service/device_manager/inc"
    "${SDK_PATH}/platform_core/platform/emdrv/common/inc"
    "${SDK_PATH}/platform_core/platform/emlib/inc"
    "${SDK_PATH}/platform_core/platform/common/errno_error_codes/inc"
    "${SDK_PATH}/freertos/kernel/include"
    "${SDK_PATH}/freertos/cmsis/Include"
    "${SDK_PATH}/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
    "${SDK_PATH}/bluetooth_le_middleware/common/gatt_service_device_information_override"
    "${SDK_PATH}/platform_core/platform/driver/gpio/inc"
    "${SDK_PATH}/platform_core/platform/peripheral/inc"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/src"
    "${SDK_PATH}/platform_core/platform/service/interrupt_manager/inc/arm"
    "${SDK_PATH}/platform_core/platform/driver/leddrv/inc"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/config"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "${SDK_PATH}/security_mbedtls_source/include"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/security_mbedtls_source/library"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/src"
    "${SDK_PATH}/platform_core/platform/service/memory_manager/profiler/inc"
    "${SDK_PATH}/platform_core/platform/service/mpu/inc"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/platform_core/platform/emdrv/nvm3/config"
    "${SDK_PATH}/platform_core/platform/service/power_manager/inc"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/common"
    "${SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/inc"
    "${SDK_PATH}/rail_library/common"
    "${SDK_PATH}/rail_library/protocol/ble"
    "${SDK_PATH}/rail_library/protocol/ieee802154"
    "${SDK_PATH}/rail_library/protocol/wmbus"
    "${SDK_PATH}/rail_library/protocol/zwave"
    "${SDK_PATH}/rail_library/chip/efr32/efr32xg2x"
    "${SDK_PATH}/rail_library/protocol/sidewalk"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/inc"
    "${SDK_PATH}/platform_core/platform/common/inc"
    "${SDK_PATH}/platform_core/platform/service/sl_main/inc"
    "${SDK_PATH}/platform_core/platform/service/sl_main/src"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_compatible_pa"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_tables"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pa_tables/efr32xg21"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_power_manager_init"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_pti"
    "${SDK_PATH}/rail_library/plugin/sl_rail_util_rf_path"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/inc"
    "${SDK_PATH}/platform_core/platform/service/sleeptimer/src"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sli_crypto/inc"
    "${SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src"
    "${SDK_PATH}/security_se_manager/platform/security/sl_component/sli_psec_osal/inc"
    "${SDK_PATH}/platform_core/platform/service/udelay/inc"
)

target_compile_definitions(slc PUBLIC
    "EFR32MG21A010F512IM32=1"
    "SL_CODE_COMPONENT_SYSTEM=system"
    "SL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_DEVICE_PERIPHERAL=device_peripheral"
    "SL_CODE_COMPONENT_FREERTOS_KERNEL=freertos_kernel"
    "SL_CODE_COMPONENT_GPIO=gpio"
    "SL_CODE_COMPONENT_HAL_COMMON=hal_common"
    "SL_CODE_COMPONENT_HAL_GPIO=hal_gpio"
    "SL_CODE_COMPONENT_INTERRUPT_MANAGER=interrupt_manager"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "SL_CODE_COMPONENT_MEMORY_MANAGER=memory_manager"
    "SL_CODE_COMPONENT_POWER_MANAGER=power_manager"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_CODE_COMPONENT_SE_MANAGER=se_manager"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_RAIL_UTIL_PA_PLUGIN_HEADER=<sl_rail_util_pa_conversions.h>"
    "SL_RAIL_UTIL_PA_TABLES_CONFIG_HEADER=<sl_rail_util_pa_tables_config.h>"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
    "SL_CODE_COMPONENT_SLI_CRYPTO=sli_crypto"
    "SLI_RADIOAES_REQUIRES_MASKING=1"
    "SL_CODE_COMPONENT_SLI_PROTOCOL_CRYPTO=sli_protocol_crypto"
    "SL_CODE_COMPONENT_PSEC_OSAL=psec_osal"
)

target_link_libraries(slc PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/bgapi_trace/release/libbgapi_trace_stub.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/command/release/libbgapi_command.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/core/release/libbgapi_core.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/device/release/libbgapi_device.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/event/release/libbgapi_event.a"
    "${SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/release/libbgapi_protocol.a"
    "${SDK_PATH}/bluetooth_common/lib/build/gcc/cortex-m33/bgcommon/release/libbgcommon.a"
    "${SDK_PATH}/bluetooth_le_controller/build/gcc/xg21/release/liblinklayer.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/bgstack/release/libbondingdb.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi_gatt_client.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi_gatt_server.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/accept_list/release/libble_host_accept_list_stub.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/bgstack/release/libble_host.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_system/release/libble_system.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/connection_subrating/release/libble_host_connection_subrating_stub.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/core/release/libble_host_core.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/hal/release/libble_host_hal_series2.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/hci/release/libble_host_hci.a"
    "${SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/system/release/libble_host_system.a"
    "${SDK_PATH}/rail_library/autogen/librail_release/librail_efr32xg21_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc PROPERTY C_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:breathsense_mg21>/breathsense_mg21.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    -Wl,--wrap=main
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJzsvQlz5Dh2LfxXOiocX7ylS1Smllpe90zUqNXtei511Sup7Td2ORhIEpnJFrfhoqUd/u8fAII7QWIlqfGzp0tSJnnuuRcXwMV28R+vbj/efPn08erj3V/t27vffvr42f7y083tq/evfvjzU+B/+/bdA0xSLwp//PZqc3L67RX6BIZO5HrhAX30293Pr99+e/XnP3379i1B/4U/xEn0O3Qy9FgIAogeyZ2TIHJzH56kMMvjk9y5isK9dzjZJRBkxxSGKbSDw3ZzcnAcgo8gYphkz7cO+okQSshXlRT0EPrfD/vId2FSi3IIcO85xtO7DD/PeLp8x/Nh/cYBZJldCMkTkCGrnJQg6KEDDCH6FLroySzJIfnQ98J78ske+Cn6yBrmZhXkGMRbJEAc2yBNkYEolZOjsvi2hNS3d34OsyjKjgZlOH7k3NsBCMEBJnaUOp7vgyxKZhOZJRCaEvYzwv569/n2ypguqRfEPrR3eZZFob3LwlODhusJ25gX5kOX/Hf163yyXC81Ki4AXminGUCVNwPpvUFJcfSIXLx0dXNyEuD5dp6hf+LMMyUnfAjObBfuQe4ba/XiFNhO8hxn0TzWAsgDdj5MTXobDKLkeV4nACZ7pcxOssikxdoS7HRrRMgBxMaqClHCyRLfvIDUOUIc2CV2nHhR4mXPc0UkIQoHUfQ1X9VJ4MGsvFo94KKIO/NSoxUW+fkxSjMkDMQZMGzLRuvQ6pS80DMZw9Zikz1ql8zGslFiLJTshV8G5fgQom48MOp7wQ66mW+036MSXPjgOTrKhTE++8ELHT934RfkXOjPPPGw/Cx3vei9RUetVjko7WHyv2yVo8wa44fykeqT78wN2O8gcj9kMwNDdpBnESoS5pi9VbQffrn+9e729e2nD385CVwieJd7fuaFzcLsl7BwI3zimAQ/agb/endtX0VBHIUwzFLt8KR5o+i2AzLgRwcTQuADFnAEoYtCCvMC9Bex12nabOrcBnTpicoSEKb7KAmMCiVjJPO6YTEU0by4TufqhWh4HjowNdEGsESZ0wpPasyhUluObn1I/5zgz058hXZfpRuvOqpF+uDYC1Hf4Ut0wNYM5IoHbmCGhhMZWDpKwM0EleTB9L+it1Td9S35U395eAEawPGVBpLtBtD2gsPpSRweBsPtyoz41ffW1XvrNzT8Ta0HLzw+WLe4hfEcD/EkVrYeLu3HKLlPY+BAq6ucRbhZPbFc7Uz91mYZshspsttlyG6lyJ4tQ/ZMiuz5MmTPh8myWqRu9Uwr6Xbq3tvb0+3FyWZ7csa7MlqMm9OJpdHOS3iEiAPQ0bcY7/5EBHK8yXj/1kPqRuEnsBsnzQF1/fPXs+3NL9uNIBCLWZQnApoNIbYjLrx2lMc23CdnW9KYOw1fLLshVOoWLUSrLBerMLLVsJVVKWsVPK1B+OE6I0P+Oc1gYIz7ALoM9dHFeMHi/1jECvrKv9IOnG5O9xebrReclYsUqnakZC2mDG2OUEmwgRPEpuhX4CZ4V6McA7QLbAOsd/neMUa7BDfCOwGBQeIU3QzzzKTJKboB5k6QG+NNsQ2wxszCfWSMeQPfBPsAIAmpk3hxFiXmlOiJMaFL7PvmNKDgBnhDg34Pjfn9Pk0cc15foRtgfoidxFwLWaEbYe6ZM3kJboi3HUdJZpR8JcGABse9SW+v0I0wfzJJ/MkUb29rro5SbBOsgWuQNgU3wdsBzhGaY17BG+Duo+jCGPMS3BDvpx0wF3U1BRjkj/fJeqHB4emQIBP6QLIRyZwaNb4J9kZ7KN9gD+Wb7KF8cz2U/3BwzfGm4AZ4B6m5LopiG2AdJ+YaGIpthrWdeocQ+EbZN2UY0CLJHHMuU4Ib4J3CAHj+LnoyRr4lwYQGBucGUmNzA+lz6uwP5ohX8Aa4m40BTEYAudkQIDcZA+QpMDg7UKEbYP7oRuY8vQTXxzuge9R1U27imlu+1Ut6CH629VvBl7gf53hw/PD3+Mlwxh4MvGE7iEIbxLHgLg70hswGjkKe/AYOfExHdedGfTBecusG45g9082HrG2hf6zibwsrZdU4VhtSyrV7228N0OyhijH9u6xJ822FUq1JXugIV6SeU2VR4LGHGB3b1M08/RtRsFoogg7UPzrjcXs3iwyFUGXiRC60HR/VDW/vOUUKEEVmDEhFpp4BqkxMVavCMGfv7uA0Y4mhykWsMWX6vmzjOXT0KtDhZCWKBj6x54+MyfgZVTiqnJBrpspFVoEos8lAlrPnl3jpVCi8fEQ73t6u4URDz1H4PWtf55TuiILVQlEui+fUAb6fqjJq4ujxVlVCJYh275g3zipyYcRJlEVOND4E6IdZPG8x3hUJkxgZPJg1vK2TVf1ShiLly9xF1+/cVQh4IgxUvYFV7LmHD/KJlxs5uiTbwjlRksGn18EZ6yQEN1Jh4SwBknv7e4AJ9CFINW4U971dgyTqTvLdCeDzF1I4FrK0VRvMaoBZlKzFkLHWSRuG6QWaES4fCwIQ8vj2jL4x7iGUspJ7VN9SsL6PNKQozEgqnM3QeKwDp3t5WSWcQF3FmwzU/xL/xResK3YQbQVFS+f5tRRugdUv3lrGiy9gkgPkJZUvIayneAlUv3QrCS++cM0FUaUN9RRErwia8GuNnmYbQLIKF+dlrPPVzT7oo8Mmu8ODdxDWea09FhsCNT82ExypNxIwii+J8E0uDRqdLlu5cJcfitVh5uRJlyOdLWGjjBlZxkn5PGxSTbZTdRWs3aj7vm7VUGMlU+d4R/qM10XG+wwI6VE/S6OD4BodB6bJKILO/TN7rq5LoZdYUwD0iVb/VcO/nPhhrV2fbIvsQ5LOda4mORtIUjvdJFOSdZvMgOHo+AY59fMCS3EahJHl5D6jvz3HxjdHuDslXkwoWW7+1gGxEqUugiyTGDwmulyKjSXNDiZe5CLL62I4iifLMn0OHSVaHQBZHsBxYIxcw0sztaZhEEeWFXzKYBIC395FIc6rplgXR+FkOXYScssxGwCR4FPlwVegw8CQZJNmwLknGcOliLRfly4hh86WFFc3SJZQH2Q9o5CyruGzfewtDH39qmFID0C6HWGkwRdkMwijL8KQtVAfRm+EIcWLCaUlwpCi1EXQHGFIcWJjGYgw5BiO4umIMKRodQA0RhhyTcMgjv4IQ4rcKJwsR1qxUdMsR6r9vq44R4rKAIimOEeUDgNDKc6R9JwhAEkevq9CovW2JIPRDU4jsvm3NjGkkq2pqBx3nu9lz7Ic+ijS7Z2EITx1SzRCZnk/LF+X5JA9xyOJLMbEV2/qivXlWqk+iKQlaIpwKVs03tU90nj5+/iIn654D1/Z/XPM35clz5i8J5q25u6b2NpOiWJgysQE5wb0WlfKWb6Gb/7Aq70r9raSol1cdex7o5tPOEuxBO2W46Ak3X7YEIKGQagpnEOdWpIRdcyq8AKrVmMot+7KVQxbGgPP8X3ZfMXZwBtqKgflvbACxroU+QHWXb4FRx31s0DqlmeN/8IKsDHnmea7BA2M8AUXay5KUnWGaGups0PAg5V3lMGLcwLJbfNzF/rYbnne8u3sk++Cv7CiOwJN52OMlhxiiWMvD6Zb1QJEUIPl1xHx0orRWfnoo7CxoxziIojh4nNeYnz7EkIfYl498c9w7NMRsNYiXHqfPN8Ew9Ak48kTeZez5PDwsfma9NSiwqZHFBxlSeT76IE5tj4iZZ0s8QW2odQE680oLQi56eAKws5Aeu/DjJ3ggJ9OC2slW1IklqIaOmpdkCJ2wkkgdsC551yUGOLSx1Hgg28l9MHzSDoWPj4tHB18BDYQTZNS2UxUgsXI2jBTpdRA+ftYSnk6CN90qDWi6McStStyRRGNoqpjCaxVM3xoYf4XT2c3MQTXmszOTbyHib55ok7gi9JV/VM8sdGgb+JWgPDhyd2DRv9V5p7CClbxctXxVlB6EkG2rpbXwrCHaLTiMMpOPJ3hRNlxpOViW6bsDCooE2Wng2EPcR2NHqOQ8XVR66nk5OYtuQqEXy2rTwnzsmvN6B1nHMag/ih3m9nMbuhD100e1uOIiI+kHxaalJ5IcbS2Vbq4teFedl3BSshVFWoTWlkojvby0sGtDbeO6sz/YK+uwkTt4nnHj5x7OwAhOAjEuSw22lqOFq3x6SpG4VPLWC2kstIOw2vxV28AHK+5iDrvGP8xGXoq3TC+nbIzV+gphoYUA4qYI2/MfQx7jkGnMe4vsq6ytl53oDHSUuJlnupBeBO1yxhrbYQ9c4wHoNcRXDD8t0iJt76en/IixpRtPNq6la1HF1lPFaCo+FpXE2wprlauMvMDXGTlZgwm2OKzoPERJqinMsG5Df+ye5KWh0u2bR1j0ea4i6y97phgq3DV8njdMUFWboJpgu3YpecqZBUuPOep5yYot+ENMZ8476eHv8jRQP2tFapUelsrBKgwTujYDIFZQ9CLWKq4RFCvtRpugMc/JA8kXizWZT968SGfwFUHuF6YwSTJ40xXjCvfT3c3uHGtRXO6hhOkXmqHqKzsBy/Jcvnms2cw0gIBfHPLoIzZ9i+yqkSPsF7NWRKWaEu0ja88k1Yr55g0mI27zO1i220g2wCytBiXtOqWL4BBlDyvb2jf5iVbYG2UsrT62Hr8rY1bZZhKIKYznldOgx4seZomwzrCaCJcnfqMyDBSPgnMQHKA0qtFXIXSFGKkJGRbZK4i0NcWd8wSR5Fvwocm5BjTxbgSBmvBwXTDVIt42VNmRioejR5nqne0KAxSb4gw0/OgFhWGZT5JvBtaqzZ84pbw4ziJsG1EYzQGmmykNlVKJUtyapvrJlKOoilBu71UX9js40xNjQ2vWTX5emXQjtM3xbz4I4eMIgrifEXDnDhXmNBEb1ddbgX0wvvYOJf2cWSNsksqUFY98o6jR9RyLT7w7mWtUL7tpVukLUUVg/4WFvH98u4jthxtWal6MmBwbl4RKkSjFt6gqVDj7z2AjJ38UV6jaYFL99upD2Fs+1EUm3N9fa5Ss+25i1mHL+7bmkOPWpQ5bdR2HYqpo7ZXlbMia6/BLY1GpK01VmTUdn3hSrvuabE7DWF6yHrmA4YqmTHafPfzybq7Tt4D0KsOHnGMC7wFDwt3T8VnkdzmhcGixqopT89TE5F2DNOzeqiLL0oTRioHVpo6dvE0zR9iyHuYhFB6jnuIZI2oa5KwgSrZLrR59iA12pOcXimmXHSXfANWp2Wb0DrN28F94XMXVfVTNFE5i9HE01+dNZI0Xks0G3Qul1Pv5lH8nXnBmnZm1Jzk264SoToY3cLUdBa4wiSDryRzHBOEW+BGmMdJhPCNca/hjbDf5SbJV+hGuBvz8ja6po66DS/fZHZoDwG/7H660dqoG6lMFdDC1F6i2oh2QVfd/eUu9MHzerq+go9sg1C8XTYGNZaepqvAs0ESPFwG9gH1R7f6aHZgX3b1p5aXrFHUPLTa11jrqEjy2UFgIJIOSM+6oalChk7kCs+CEwOUa1a4eCuUdRQtw2ThQ6B8MZgms2MqOHspyH3hIXBhfYxAbN+F0tBGYkgNrDSysQ8whIknfOxyyFYNKF3sHOAcJWtRm1sFpIuZRHg7xEtfQpMSzt77ID1q4laD6WIoc9Z7iJzGk90EL9r9Dh0tTUaNpItbDA5aKkGJo4tXlgBHC7EKSBezPPN84XPNQ8wqoBd8iq7ZkZX7XnCCZvF5hYaFcGw+Dqyrv1TnqJEN7Ug02K0C0t/2a2DXAtPa9msgpzEjTrPF1sCsRtLa9mtgVuLobWE1EKuAlmhhizsqtDWyE9dmTFulALA6YOsY/KmM631vJz+uF+8Gu2PxQG4JgPAmntpEECyNHhUnyJWI0PdVaUBFGlAPDZnkXi0ekmm/e0SCVM0/6PuqNOJEolVt0KDvq9KQWaps8ZBbjuwTofePqVCpIVTJSC3GtbgIL7ipp5XR1XgK92pYbTKJ2UDQ0XiqEKHva6CBBzwxkJgxaLNpwCiRwstqqvZpY6jaCKQpTNTsU0OoktnlEtMBLQeWmQXo+01xIkjJZyoI5TYeBPs8VKvYDQxVOg8wSSUOhrfoNDDUiyqRmNtqFVQis3QzSER+mr5DSH6SfjiCVOED9bQzMikuWzwk70oZjCBVeND3NdDQ0Te1YXSEtSps6Ptawlql9o4CaAhrnb3ETEGDSg2hKcZWJEMh9JDR0uD1ofQMAFQ4Ce96mmF+RnDjRH9+J0nCyEb/RvhcrSucQ9TYHowuL9GSozsxejhFYQ6hr2OqjmFW5Yk0fNEBDiIkcxiWh7Hp7RgdpBczIqbcJZ2pvDBCMDqcoRmoU+fKNwU6jFtsqhaurDX90sYNIMWxNYGSCTSHSWmJOCmWXCQxzEtTSFGjSYQVTGY64osWmmyMMcZQJthYQ7NeeaVgk96wBW3Wm0ga/VsLrxpLo3/rYiY4R73Si6+L3NscEaXWe69VI1gtkRHRPEq3U/mFmiZiBkcDYC8qQOryZ7Wxo8YoY6UBsL+HaiJWP66iiZvkGe99DB0/d0Xu3BxI2I9ngkaT/5HHLMzRogKt/pvchTZEYWp+mMlAYlK4QyD7A+/GQAMV9pTagPT2W0q6H0amrZh6H8SmqrqCyfAsOGNvWB8S3HxJUjBOI4jP+rwVEdx6aVqwamVnVLWvd59vt4vVUdRATpiM8Ot4CX1LsrCi1M68kR3dQ3Ib72gpKYZNb6M8EbpquKsYjsm8kR2LTd0KYVb7LfN+KNbp7BMIJ7Pk9N4qEivIeLWn5tUgi4KR0VmpjVUQtKg0q35NtuVLojzzQvYED0ty80VJ2S6ME+iADLp4YzXOE4F6LvZUCIsJG0aSF3yAYWYfkIKxOJvuy5IcfkbwuLYJy2++KCnb91J238+SW74k2xHCNAUHaO/y/X4k8mJJ77+u0CHHSZRF47fFMXn0XlfggUfwwPftMA92cGRNcYzMAIYCo8cExLEslebLkhziKMnAzhdvrZovyspOot9R+yKue/NFSdl/y2EurnT1lqTUFAbxUbwu1q/Jys0AuawZdTHi1u6+LMnhFsPcyFHovCtthQSCQLZB7L0tOxoEKTvgZQkvX5KViZeNxc1ev2Yy0i5bEvn5txsY3IBQ9CBGx0ZHCGKbfV6sa6OStUWFW/X7c820/XJ1pbpU/uHrjX11c3Zm/3r3r3ryaIZRaKfQyblmmziLBttavGCQeaymflZNzSoRtaUyJlJT9nS+NEsKqo1oM26wH7a2dtIMAVotTToj7uaM29YVrHa30E6Vguq36sSEu5ptZXcfU8ov4G6WW8/3nCj8BHbK25jo5hYdW5nwlBJnKn9mATc0syg1axh3HbuYBAKS4fkbXgs1X+CIk0ZmRngldl8SlkqmFnillQ8LSylGS7xiqqeF5bQjc155vbeE5eKgnL/QqqfF5RRhOLeg6vExSTILFNPLjowX1SbT65WGSRMUk+p0Or31nskRjOL6S8l+dAmmo2K5GtJ9V3KAWMEE5KpOWRLV22tbu9j5OcyiKDvaPrQDz3V9+Agmhijy20R6bx5Altk0/57tQvLDC/FeBXLJsR09wCTx5D0o9W1eEcyyZZio3EzBi28Jclmbp5CQ1cue7WAH3cwXXO1S2YVUSlbYh0RuCo6jEIUHyjlH/dICdprHOArUdT2bdM4Mhut7FVHgONCHSXFxOMvPuwXcTJBZfGM17Wj1DVHm2RgTrW1g1hQSBaEX48vRQ/Zqkhn1OpK1ahenYImSGxI726iUVen03mlbqs+MmzRYtLy+o5ak0TlIITnJc5yxtxbr06EtTLuPz6VHV9rSTq35RuHK1Qw2E+VtG7Ukbd4AIOosRrLLamLfEKONuuMEc1BviNFHPQDOLNwbcvQ1IJDOrgWGO37i9l1h+tQ4gs0cZdCUo5P89uJyJvoNSToVuNhsZ1KgIUmbAod5Wp+DgdYHOr/H4B7OQb8jSpsK2TGBwPXCwxxK9IQZCinNRxBtYbrVeAB+PrKlTq8atTBTkbFxPbrS1roIWRqrPyWD+buJ9yB8nRoLUu+AszBwloTsE5cShVkr3RrhlGK0u2Mha/xaU31qdKSZ0mbiVKF2fcQPHnJphMJTeiDLdmEMQxeGjge1znAM6DUiVXeb7mWpPZq4XIdGPUm6y4g6wS73/Izcrvk8QxExhBrSDcE3R0pzadcXa1A/1Fd4D8Xs6Jz6tcUa0g+gEHM2rUphhnQJADvdrm5VqCxDmqTeIQRZnrD3jejWpyXRkFYOydkwm0q1ON36ZAkI0xgkeP/RzLqNip5Bz+PY3RgmtTwq3KMhqOM8beKI4Bl0nKWtZMs1qeHcXfa4bN2aRjH4Wz5vlzco0pBecxceU6zZcpuru2BJNavdPA3osMyXvs7b3UqVAgW4wSLzwgwmIb64PMlTfLo9zaJk7HY8tRLDk47oT2tMrLw7Mp1yIS2nRGvWlGRONaxSJUOh0ZCvYMwC7s+ymTMDU94ss3pm9RqRamoWdg/JUNO0ZgyJJmdSjBdVR5jZkfpc2tTi5pnFm0uvvth5ZmHn1M/UNpnebNtcSlFZhiJkfNHLeDoibfoMSTSk1XhSG90aCefA4dWmOZKfsaCYYk3qN1ORDYp8cTsOPLpdYpXbDSg3e+RkoHhxlhpXuXSbMl76GLtXN7RvvanMV1YFI9ufvEaxGOduix2tVK+G2nYL4bxpTuSvuQ57XZZ2AlARAs17Otoy6g0rI7K1umsJbGrLAEM/hli9w9u2bK09K1+xaW9chsw2g1oMsWtteFaaHL1bIHY6nX1AIfls71Weg8Mj/gcEglOqWp0UkrogUMqUCRIPqFOgIJIcdt4hzNl5k3hZ1DCyPPzIuRedFWKy6YDJcso93yUH6tUZtaBkMx6jH76vwWeaQLJcHHWnoRiyDI4A/W97qk6jAaTEJY78Z01sSihpPhBXAHIIWwOjNpgsJz11W7lWOyJTfUwWgnN4vVsbsDFt4P6ep5ntwwNwnkXDOia1cWydjPdJFOBZGTOcm+haWOP5IwJaCNDMegBdG+s0x1keYWaO+YAELezTlJ3lSI4tRdTC7uni9J1meiWkGj+NlUqtBkHH1UClQpFmQU5bauBR4UgziTWwiBUYHDREXgelyKsE1xRf9OFkefGvjjO5CK159+RfaCBwocCguswQ5yZU5tJDU2WVZ556b9BDk76RwX/enJ2qF1kTSPqGBryCD0mepFR9WqIPJ8kr8WIYuJtL9UFWC0n2XoEj2CgTKUHkOWwvLnWwoDDyPNhXvgmwULkCrkhAoYMFhZGdR0tDdb8oQRQ4PCI56q1uC0l25gqk8PJcfdaqgpGOZoMYZK+3J08aotkmlHx0nWYAbxTQ0T/20GRZZYntJjsNMzUNIEkuLtzl6kQqFGkW6p2gqzQ37x7Vo2yKIT/yOuoYeB1VOIRZEsXq8w0NHFkmQtvQmTxEN5p3WBzv3b0yiRJElgNOfaaluWghSbLxA/WaSjFkR10wiJJnml/eBr4fqU/vMjAlGYYwQ4Kce5ip26qDJcvISzP7/lGdTY0jySTy1AftFEN27AXVW3qKIcuAfU8ZNwGVW8vieyfVEMfXMAo8NAzHSxQFFm+0sHijYc5E23SJCpcUaJq6aQDJzkhomI1OlOaidaxoqK1hpHifE3CO6iOYFpIKG7Iom+Zo1KrexQ0BqnCLontPk6kqKAU++C4nyL/NbYxPDSXJp0oAqUynhSTLxgu0UKlgJHnQw4rKRBo4kky0rE8qrkji120nUW/0mkBqXNRrTxNIiUuqPihtAk1zUbj/VeCgf3eGSm1rCj7jrb4Dpdg5TpfZQY5+hyG+MU9+AFHzYsFq4UoX4qVOXE9TZqDrZI5PYcbASwSPdHFz7+PrZJ8+h1H4rDBPweTdRF5ujymmp2d/aaFjmdeRbKVPlUK6huWGUfUwjRPU5Wfeg16mbVQ9TCWPiXOwlT8JPsy4WG/RwbBGUmWktN2kxUh1L2uBI5ccZISYdPaPCX5hBp+yVHONHkfXy1x/vZmWoFcDvW3UOLoacwSYyE+yNEhWQGp8FPe8Ngip720tcJQn5xqcNMzPladnywQTOmi1wBR5eX/ocfoKSJFPluSOlp6tRlJjpC2s1hQ/C953MUJI5DIL1dOLpUadYa/v7RKQ8Nz2ObpZhPcQcWkMKtbqoXAYgrEUIEuhCSAtvZi4V6VQoYjzKNcOpCk0AISl19ObsuJbCMLyge8dQqHj0V35LQRh+cVOsCrvoDSLARxxLuSsKYp9EvFZ/YpHG0OWg7o9+jiyXIJIfCKsQ4NCKDCwEyC+q6DPooRRZILs+gBSFMVootTCE+fWOJWswXNYaOK8QjvIFYhUrwtLpidLlYb3VT87jCXOqbSooucM4MhyeUyA+KGjDo8SQ5yD3ORGHf7wT2WMxV+2F8TyPjoMpcpItQqz4cSZZeKjvopGxrv0NLBVWN0KfRhhJtCJ65TIIvcmdrkMAUmyUWw+uiDiLIott3Yc+fJl0wURZuEHkcSmx1J89baw3MCVOkJbCq5fl5Gs1F433heXHaeyk9GV+BaEFAO5rdpNAgLbtAfk43GWxCRYk0ANIcUgS4AjX/VbCOLjZODiyFBaeuN9cdn36t1BB0OGg1L9a7wvIVvuCFgtW+DgF2N+REMJDCEJ80kQCupB7SP0cWYJaTYDOFJclM3SBRFm0d3XqE5pFFGOn++pTDK1IaQYFOGgqtcMIknxCbxU/DxJk0YJICUdYW7O1KPJYSgFRuTOT3U2JYwwE7JnTrn+9FCkWt1yzqHwe5Xp6R6SytyotsmvHpjkPIb8EorApVIjMyhq4isMBR/R4ByKDMQuzhrxUf7LsEZqjJpbDCKp8KGbKnBB4y7DDvEKL8g8/gvwRiiOgquwTv0ok8l2PMJ1AFKJIb2cSgezGkqFEc7ApIENhVFhst+7/LedjlApcVS4CN28OsKF/yJVNheRaydHqHBfJclmQhKGaaBS4qhwwSfXNFChMEp1Wk91VraI0J1YU/2ZagQol+GU3Z+p8lFZIR/AUeWiOjfJhtPY6+tgNwBpJi7Rz7UNrtrHauDHnSxxoo/VQKXEUe5jNXApcVS4KA8QGVhKnBSWi/owqhGIBibciaInIhANVPhTn45EICB0o0BtNZ4Npxob6WAkue7Xjmo0EEmVy6o7jNNBqg+pY2SogxnfDcga7z9JgOfbPLuLe28WgYv4juTUt7FQprmajOjOG6vxjvh8b/GuHezZRx1GZJbvScsFaQqTrFgORtHeWFa4MRrDMNKsxnfrjxER2J7PkD15r/GYeLErirtraKKOJ+11Ui6n5G86nE2np0m6maKPyTuYkHfJnOEoL/KSuSZq5/PcLjVa6xAEnz1KnhZ6w+q8LZvwSJ6AmHT5xBIehPDt6XZzca5q6BpJUN36RWsYS8X6OlhJUZIvksdgl0vfjFZakIAIqkzesXoIKuaXpyHKQd7efzyCB+VmhoAIKkresXoIKvaWpyHKQd7eqefCR+Dfq5q8xBFUt3zNGsJRsb0qHwkyho5dOkcvlumu4T452woU69DrT4ftk+DduQz/wFrYaQwdbz8y3dqOidArFqFhVWQsJh6vs7BdRhdFNX6z3VHKKHecuOkA+cbUQweEke4J9CFIpVvxEqa06MY+OE4JegJ4yoUqYXUYWZPQi9Xy2M8PnpTVyxpBdpoWKWI8FKvasXSSMjYiZ2tKdLHYMCNfGe/vmpJjgA+40eyCylHeACRzaXfSXm2cse9ErseeYJ7hdG3mSNfwmvg2rSDtmQKWlo9Jeqbgn5OQMbTA1IW2mlSUrnrAsdETcJS03F1gx9EjuZMx88KDHYA4xj8JX/sUfa9UDoXaVfe/6T3ASUApfhGUuVlc680Sam8XV3u7hNo4GAoiF7kaMvsKjMDgs5hJVmWPJY2xLu+Q8Q3u3ozLbjRe0WANNvJ8PTQ2OV1xxtkUvExPvNuDVQgfe1hT32uLJfvI8qUursWsfpB5ego+8xRKOvN6H2grSwQlX3hDxOYsnmSP2ofsqKWIKJZ8MVGAwQ91FVcJJ11koyRnmbgV2+1SbcVJYdkKiG16KVPASU0WUeHyw7S0mLCJQhjy9yBMNlwW4MdLHCkglpfW/Kb36NfPVjn6qi+tptGsxpOIsNWTIxb78WrAmfNPjxoC+QGldOE98KZJG5FTcVL6lNc6zqVQQ54hjfiOQGlSh/+clJQunYzWc2nVF2tQvyMIXZ8rLadG7ZpCDemWeoeQbKeaTbGWRENagSyD5HDJjO7YkalRM68pJkAx3C56MqoWS6CMToJTDm1DdPd/hcbil8mN4VLmRIStnhxDPu/CvRfyJNPWo0lTniGNOLOVa9JHOKW5oDZ8F1tqUkb08kvRVmhy964OhZgSDZVQlZCRL+mMpqLqSTVVZvxZbHSVmVjGG6kyo9l4OVP6aiqyrlBTus2slXF9OI+t69JH4Gy7lD7lKHEuhRryTI5K51KH/2SxlC6iNzlp0kr+eicJ/aoB4pzaNYUaH5XOpVhL4gyj0rn06sg0PSqdLbRoCJxtVCr3Un+BwLNjpLIdpYDnnBkPpN55/QY/2wlSL7WTLEq3WqccmkKqWQem2L+ziYeGplprTMuoZaVpidJa/4eLaz6FumLX2hDMdmSB8SXr43aJgrhMVYc693vooo/2wMfHFKrixC+8t67eW7+lMEmtBy88Pli3OKeG56DCuyWlbT1c2o9Rcp/GwIHWLkHj9mMKQ1zqeLsTFdMtqwEyx3nIDDhO9/QLBG4ATwLXPKGGqAlSH365/vXutiR1gCFMQEZ4ZUkOB5lO29zeJxDi+kQ9QQcsqtEHFIWgap88eA5EwTH5ga+QTgISmNjRA0wSz4UapaL4IFSCg0/kjkH3CyqgP3kBaq5o4dhecDg9icPDD1brGZH3N4rvbxXfP1N8/1zw/cpZBd5Jq5pjo+7D3p5uL04225Mza+fnMIui7Gj70D5GaYaqMdmVtMtOntCv4zLo3ZH4K601d8CFhkQ1e8SiJqR1L/gT+QBJRnKj8BPYpdb1z1/Ptje/IAEfCzQJOdWdiEUWBRtV9BQ3fWVWBTxZjP+mWSXUJdQa0b9J/CSMujug0rSrs6f1aXcdaLiVs4EL4mJwJAta+aKapj2X1oCD72xOIt8vBlBqpZrAukyLRH7WLs8yaYUZ0LSPsBxy51xj+GdaBBlBCYso4k+tPk8grStMWb7CFyBf7z7fbvU0G0MGpP24kUKCgZs8qBmSiex7O72QlCYKYcKomZFHUkoZgln3MAmhX152rIJU+IO8J3QpxVFCduhbv1xdWR++3thXN2dn9q93/2qFqHshYzkZMa3WK/Bc14ePAFmaGpg3itTe0h1i1PtrdZkYJmRxAsh2ZhN1kyy8JXmcmW1D+2Lk2lEZbSyAd/hqLmkfurjhkTNWN4fg9OxGnW0wj3GdsooluCVloygLplAmBmSlUJRvvzQopackO9kg9Xt4AIMoeTZbWTsyjNTUjgwUbOOhlSmF4txE1BE+BGfGcKUr+IQtWoemzJi7LQJP2ZfZRc1LSn0IY9uPonieZgSne6VdgpwtB5IXqqI0M+5pw2pm1NMESTPCaUKj+c4UC2AgDZE2hnWGMHnPlF0V1T6IMdJy4H4ZeIbB5fozsbw8JgR0c+wYkVDmHjEIbjXykxgQM3A624AUfPZXP2x1ZlW/76NuEd/pbqjLb+DLVS/xrtejadbnG4OVDXkpWFFThdVt/QWIXvXBMwM7AE4S/YR38Xt4/uRbtXZWrTl8ON2c/nyx2X68wZkS+QFuP9lXn3+6Rv/cfPn86/Wvd/btX2/vrm/IytsD8HOyLvicZnBoCC8Ae/Xp89U/2Tcffv3wy/XXFnpreldYSIX/4e7Dp8+/2F++Xt+iv9XI/nT9zx+vru0v118/fvnH668fPrUI0wmtemZITdjPX6+v8QSw/U/XX3+9bosqp/PsYjpPTdAvXz5+bqHj2TI1yH/8QMrg5vOvLeAj8G1mKC0I32ONwdWZf/z17vrr19++3A36ZG8eS0TY1c3tx1v7V+RC9j9//Hr3G3Yflbftf7z+8NP1V/vnj5+uWyz/v7/lUfa/iqWNEPmk/eAlWY63DxXfiIi9+cv1T3efbpGFfv354y8DsvzsfzVmbcod6H9SK4Wb65vPX/86WATtCQo1MV8+/wuy35CUVrQiY68vtx/sq69//XL3edR0rXvK5Ez39cPHT/anj3+xb377dPfxy9fPd5+vPn+yb3/78uXz17uWxFPFLuB60FbNHAdKXcHnr20D4R5Rxhi/3aF/vnwoDV9UkyGv7cbw8vYvRX759NsvH38VEFlnXlSSe/fhL5+ubwU1LsJ+XXX29tP19Ze7jzdd76giUFX4j7RCdeDLeFMM/iOy308fP39ARvt6/X9++4jCA+Tct//08ddf1HlWlZBBuBOwKjZit9dX9ufbTjDS2J/cA6cjnZ+L7VaT+yx2uee71sHB04VJBp9eB2dn9JkswTtpGrmHGx/bCHI3lHFYi/zqWxxPgNDtk6BfzMEgGbABuQnTuOwi5uxLLz43Lx8+4HFQTzz52Lz0ntzyGznR3Z1AeJ8Bw/nL22yaBOgdo2qi27t+aulPxd7SShze/YgGhjBRl0d2KzH0TDPg3LfUjELXCw+uZM3mlIu+JQXaklx+WGxGdXxP2sf0scDDdLNlABwH9Z+276VZlwd+yW58r9DiyvsDfWG5gjAtuZjl6IouPjUpGzUDIXTIvpg0R4g4k+igBww9aNwVep1ezUa23+MTjIb5g3Lx8B/VRg+mW6PinZ4XFuIdo4447IREsoInmrlRoiOWBq7oJd5HuR8cmnscfDCMkJUGHkaW9z/HNMLGf3wkRwyqT09y5wT/5RwBvroCPRSRz8ceO3HivDuMpcU4F4N9h8E+frh4nQ6tvJsR70cAdUw7rzM/lwydieFhgGfc8S6UcQLlUyfF9kWyhbPFoDg6IsWAHDaZkF88Q3/cOokXZy3x/4Ci099RQ92oafhJvL/mxJ/JNPs8pD1F0WOkugwkyMMFGViaQwjCyHZw+6eNAT5+EewmKVSPmeAg4KoGpAuWQRR4mb1PUCttxxGZXV/KGSIbPuFIekmHjOwky7wFHKE8YHcDYtJxLqO/g6JWELqkn2j2n5u3M8l/emIw+J//c/NmHg6PIAlR/J6eAN9fqBgqCvApS8DSJGLogjDznHZAwzjyabRAUEhBzoakS1HBTwTeH+SsRHtO2ftjhkbChHjRsAHu8gMaKT3AduVw4R7k/tCOomESAbiHJO4CSXCCRiYnGUgOMOuyYDzWi/BfB+iTHyXifEUe2TEPdh0m9LN5CHQHGq8D9MmPdLjx2t1czkZkcMiB6ODPX6PPfxQafvTE1H3EJKP6UVaH9jrN3B9FerURGXEsQAgnbmD1cQUpoY5OM62h8Of1PoxeF58uRooRFxJqze/m9a0yZLNZo13UKAUCPZNGu81ITcRiZU9ud0Or1/9CPpnfUOYZSdmnH/e9/hf62YI2MspKxE7MOOj1Zy2tgKiFTPMRsQ17Xuf1Hn/3uv5ufkPNSk7EauOzcq/35feLWm8RkkL1cnwu6fUeP/CaPPC6emCB6roMTaFazBhmvR4692i+2hplI2IX1nzpazTagU76I/7+hPy6hJ3mYDc8XcB4jL0UorYCosiK2GlFVqrC5eJvOwBxm9n/pXjfvnt9A+If/+G/ff7t7stvd/ZPH7/+d+sf/tuXr5//9/XV3a8fbq7/+wl5mZN3sRR8gtO20aWpLmV6pCGK24EFWQrGObPA6eZ0f7HZesHg8RI1c3kpK2UnAf7kpVkFXoeE/vevXz8myEwkE55NrNb4MECBdeT0PnaGP05g+XlPOQEmAVk7FQbA40t/aHcon+iDM9YTW3XZCJYa2e3zX7fYxC2HGumT1PPBLiVVLfXOtkXj7WYnxcZ5l+z5ICvoJ4cwP6mahh2g+SkbBm7A1c+eFA+gVnTvgwPrjvq/iwIwXW/Q23jM+Tp5fEIV6BDAMNNSgSTcAHXqAo5Any5d4f85wkododX/+f5D8F+0JZ0EaMQ9xnqzbiStpxCYnjdP71ENC7j6j9b6Imo4sMonUXaECd5UrFH5yTeZeeLHpAUwTZEVXvswPGTHH4fOuM3UVguZvfn8/zM8s14yd1TJVcwn9EcF+frRy46vyTjbRKv+YqibC1BF4RwvcXIfJC6MYejC0HmW336yHq1CNGJyexMOYhtHVKJHDarUkahgEf1g0amF6pPvfvjzU+DjV4qjr+ilzckpAUFoET5dhD767e7n12+/vfpzDVROUVSbunPnJIjcHFW5FGZ5fHJFzl99KR77gmz+F6JEN8/3CdmJjmAQYAyT7PnWQT8RXjUH0i2RGGERg9xmMP4T0qj19wKaatDRMs+Sbsq5hVlGNlCtkmTuUGNq8JPunTN0lpPV1HcfP0l9smEkg6M31XSuSThxEqc8wu0kBWPsnMjmVXX8NnSFAqPD57yAZEZvBzFw7u1ddlUoOX85texNjv25uxN1Sw/jHuVxWWU3loKocyZhvOl+9f0rOtlsf/38+e7V+1f/8e3V1+tPH+4+/vO13fzq26v3yDVPvr36T/TO7cebL58+Xn28+6t9e/fbTx8/2zeff/rt0/UtAvg3hECVvS7ufEC95Pt/+/fv8aUtQfQAXfQn6Sq/rx68Jblcq+cKZyESS2d6f3NDPvwOeWSYvqef/oh0eHXMsvi9ZT0+PpZ9IOoOrTS1ynYAkrQT6Mm6EL5Ri+MPPZf83XXS2AtJbznonfi92A1aQH8iNg2/o8VDkkB8F+PL3pJC4sn/wP9a9LmqMErV/vTtVW0RpDzG/c/v/06sKdKVvxTj1qtejSbk+/6nqAFYTTnwNL0vxf6rMerLcGs8TCDpxN0AuMlD427h76uvcOInz7G9bdr4mr8+UJSfEwhxorOrAQn1nTaDBHYZ/qWoOsVHeVLclFl803x2RA+c2Nmm4ergAwNpmjp2KJN+DH9ZHfIFLoqOMi9tXdbMeJbngfLgN+vZjCYJqG7JGXmSJJTj+toubuvrPOFkic9+n3ybOkeIHTGx48SLSLZFxgut7H92lDqe74MsYpqt/XyGZ75ZT0YJ8zs8UY1DcORuGUjvmY91sp0xvqar56ynWonMOJ9K4GGkEPuVsfV1OwUr46HBnFhjz3SySLEf7SWA5XgnY9apXnJW1oPkFjJoF5cdIUcMT7mf3PA9Of6QD13y39WvnA+6XjrybJVOq9PkrqJry52/h0ihjsmKW+9e33768BdyT2MjXPt6d21flZlgU1pOjH1NjW+aDXgnAGx9dex+VWWdtR2QAT869B8hWZeKy72LnW1jX/febvu0F+JTIsggfRzWgyxE7NPTcO2nulhep8216VfTD2YJCFOSYJf9Cu7eqRtM45NYoPfQiqrgHQxwGmH491IJsYXp3I6Hv1uNqamIG5gBvH18nfZu3TOL3hq8CHXwmw3zmy3zmzPmN+fVN9LXgk68HYHEpXd+pBY+7keuHqOXgKDQiF4/jaMkWq0VsIo7TcqIi7ZqTLzRa2WKgQlhV/w6xY4XLd2ixvUQoipWDn7onzoEYANQurLK03v80G+2j6CkWWEcTKfEkePTvtENFy5OKRUnstZi4tkwzAO9qHmKhizqiNSpS72V7djAKxg6ItMD7XaL3jr+fXWz+Pf9+65X0byV91Z/37p2fLS10ZtvVVWUUGpVjcLGsqhqEzOdMFWbqKncqNoEjaZBFZDSvJ65mtOa7CpHMTwpkIGbnWssu/PtJHY3rWuNVnxgkwNGwjDS2WGFpBRNaJdskYxvqoFWzCorA116Tmb7nblAeahiXhH4/g4495P9Jh9craheODyLrIkiXnqBmTQY7XspGJ5uk3WXPhKZHPUxORFI8YjeXIZcDWInkuEaktBMv6xDxGRqXeNCuumcZxJYZ27WJHAqT7AGMXpSAmshMpH9V4MMzkS/OiSN5/TVIIErfa+YnLqn5Ymvxl+v7kj0fPSuCphcr98BkQ7w+lCkAdVAqcAhvagCSvYcQ7EOvQNAt9bJQnikvBvdoZphCjjGirYkmrwvk/fpxLxwFDaAM7i0LofmPocAzxTijsfd6UCET3iuGLWEVUCgA5XyQ9ZTgkHtJl1sImvDaljt7QtKWP7WAbEOO8XgMdHs+HjWLHKRj+iFTZ9DRxqnCvx7LbJw2F9DNVpSSRRWK6YE17O6Clq/9VBBG249VBDZrYcKarfaK2F1qr0KVqvaqwAxqr0SJLvaq8A2q70ITuC5rg/JWhedf6rGSngnE93Q5IV4or/YThYh2onnklu8eZ9VX31bbiWP3KppXeHxz8diW33xkV0d5pwgxATAJ7Bk3+WMC4feJ7vh0BhF4t0gzm2QBA9vJd7N/iBTTKgl4nsZbxDddrSOqm2IQi+jrizznHuRV4t1KfwmHq7hl3ncpJzDrZbGWhPQdqUEfY6LEAuTenEPc4JnUUsbl2z/VKyP3KKRICqfT2CXWtVl0pUFq/w/qBsO4ineyjKmx0yqInb5frLyqctIQDCDkMy4Jk6QmxaB30c9h3ExAUCiUpKgLJpsupWlxb5vWgY0XzZ71NYYL5lD7CTGHRlfFz6HDDuOprdnqAo67mcoluP+ybgMb2u84D3gmpfhAOc4GeuqSuHZOKVDxtMOGG8fSzl4AsoLzff6PiQb6Y2LmaNi+jNUTP/h4JqWEaTGKybHlj4NInj3WqqKQvGecYulMACev4uejAsyH72gAZyzn5wMVZUyS8OSz9KycO0tVRXy6Eamy6SZq9aQqKDcRmgEvlgptiuF9EqhUxzk8GMeN6RonUEopXRVmRBSbvKlkzKlRcqP7SDGuRcm7DEFwjGd1IGg2tSzUbxq3MMkhL7lJFGeoUhH9L1ilv2A3o4nJyy779JkINWpa26VO+/f4nWcG4BUmOziWBAgizhmcFlvV8aTfN+FcQIdnFCliDc9klxSFq1VJJIYeDFL9l2ajA/PZO2nex4mSpwXu3C5diqMoeBuFvi+HebBDk4HXGNQOIVorICBB98869DM95Pod54NBaz3/5bDXFo4Cr3io3R5FoutgVItTbMEgkDRsfCGUel3cSwlTJ9UJsG2sfQU65erK+vD1xv76ubszP717l+tsLj3JE/aLmk/bG2QBkbkkDkjU8AmSWNswcLixiaubBadbzGGKeMGBjcgPFhHCGL7TNrIzfCp2EgYWHjhqZ1GQRS+aIoEX2o3AIIv44ovHKPQGs9//mxsma1IHyNwOG4UjCtk4QTbTe8m5ETCN+zZjo9U9faew7VTihuZpzbwg3GtkXPC4XOUmqBSntiLFysDWS5yvnMEzDNRtHStmFYMxVpGwVKe/pYXq4gdRRsAG/XJKc4YVcLh7DCNDFKNXwUtOImMrSkD3jw3S6FhkuA7R/FF06Ts0+KIdPdTNSFVfUwmA9NxoHLbQZFTiXRTkseG6Y6cIqtI1UKSvyQpDiISEKgTuNzaWCDqUL6sBi2qSsB4EbK0AM+iJwcaJUnQlLj50K0SFvg4DYwauTYctaEuVKo0htOhc7ug5VGLxAyNug1xGyGp8X/xpBQYBucDtJxGbkC+HdTTmNgA+Bd9SDbXKrMAHk2DqBGRJC4WCpqnEI9gcrJXDM3eowDrqBETZyPUCBftSJoifYAxGj1qhCMJKDTi4fhKrUEgeLg5INVNuTEokWh104dXZx0lgWZ5yYI2/Nq59WES59YHR51bHyBxbn1whTNqSHKkNDxoIXFt8+QDkq9mDRiOHaGcMPQoqhY00amLESTpcVIPR7k7bOBxbPbkgVEYEehN4kVxOPYAccJo9Cb5RGAtmAQE+KJ0LVAcO394cPh2xHAi4bPs2pB01hWuHTk8QJxnbSah8OSehqaTJr4regSVTooCYT4aYKAeGIXpBV15AVs4uGnSACOfXa8FQ1oADTi03mpAKmqZzgSM8hHKMJ5CZ/eSM0QqNfJMSPnWfgxSsdmfK0WmQts0T85NWuaaIeVbionMoBKI9LCx1br9oVrdaH4oWfL8AriSw0hI8QzqUa7etAToLIkhAYUfTe6VVJfDk2NCjxRzKnl92xnwgK6UUidFUTQFQCmr3CmMTEi/qRsEYkGyHfiJYzuwoNwANGTiI5/KRdWRQNuD8r4XhclfLgHyw2wueIUIiQuf43yfCnztVPNI4cvqJSaLtjQth9LqsW0B8oMjLniFQIkLv1HialK8MINJksdZq9AB3u5AtviH6Cn7wUuyXNm5hkWlOL9q5wvtgqjxel8obuCYEuhpV619N1aVFKb16Qwi6KVcJiR5fVEZDMvEUjhBr16pcRLhS4t64svPDUkrHaQjjWQslR0SMWSW2X7aTmJeRJXFK4H4Na6sVjrEkoNRM8kpV1xmEEer3CySMpAcoOpIYlBWt3rrrV7DMjQVUpxXjWEsO4HdBCuNj48OqUbnrS3yJc32vnk1wtMC+O4UkBDjGVQEl0G5r7N/W6QGr+EXB4Nzc7K8Qd3wlaQP+No03SYlVzbafhTFfT/UreOILOqSc0rUMi0yIbJbmHpKMS3ugq3aOHwvrIYJPhYsbaMNoBcnajQBY+OTczoEWlPP2ARvmdoMbGlq/ejU1DqBPVMu0oLX5CPlxbT1mZryE93QnhHs6iRLBa1alGxourQpv2bPLQQNpmaQorASzS3DSJl4HSmK7pS70AfPZQ0o/tIDSW1CIdWsMARJMrleBiQN7e04Orl62/d2CUierfrK4x35vHHHBfm7mtTHyOW3U9ddtCQ4Ry8u0rhYJdhT8QT+xk5j6OCjcVNmnsZM6a3iCrD04i/0mex7dJeoyFkvJtQegixPFACC/eT6PvNdrmnxobdpMSi8qsmGJZqKGUsMSUuWr4sbM/bzg1cD4E3MdnnNiw/tGIx8pSwoJldk051y6dh3Uy2ZTlGGtSIH940rpMcTKrpV87fpPeDugmJslcKMXCAVgDjGP8mb9in6fg08Nmshsl0LEdwlB/jY+CkyzkpprY2TAUMx2gdlAa3pDjw0nPpevUkSF6msZeb1PlDXYwhUlWmyR4WbHQc/VGY8Ci7EvLpK2IfFNxwZsdgIJR9pEA9C+PZ0u7k4Lx6o/1bGK7mpQqaeCx+Bf198Xf6liFWSU4N7DHZ5WnxHflVBKRkpAP3xCB6oV5FfVVBKOlxAJHcT/jjYQTfz0+ZQt/gG4+HYNgrxZdx4+qt40k7zGCdbKo95k8kw+hW+W8qHCVeuFTMMoiD0YrxSHE62pHoJxCmYW32yxQYiq08fOtckzXGCOaUFwJlRHHR+j8E9nFHiYVZzpuUusGCeykFkHsFmThWPYHtxOa/Ai812ToHVx/MJxE2bkzzH2eTmVr0yH4CfT4f92mR68yuaHRMI8D2CM3lQuehGPWgixtYnsGHYuWR6ZoWWsReVUAttf26gTDklo1jQ9SIwPa2mkUIpstnPLCvdgPmRV9FcVLgGoz8tMlk+jyiyERjfP5oleYoTcKdZlHBkpNEjvdqKvAiDsk4XH5X7quYWy7ukoUcwitmoXIA6irllOuRwwNxS7+Gz7UKyGcnMOGpS+pwNSFs6GvHMJjKKwd9yaOOkGlwJ/HUL5lqP0SY0S0CYxiDBlw3Mr3JT+rx60+UwVKNiGLowdDzTwhsxn5fhoz/TacR0CBzqHOYWy7NmoE9oloSTu1L1SOt0QzPL3OWen5Hdds9Gotkx2bQLnFlqpwtcQLrZCH5MOu4CZxZJ8qjiqG42wbQLXKJStUXP7N9t4XMWNZW8UM1q9v9LFPqA/JlLfoDBkSO5pkn5c7pfU/xCPjgYCWoX7pXTMlUSFkMTYQxB9vRddAqyykQmlShB+9lpcfFddUsXZQDEg3ImVOJNbkPkxkrDycsSRbAe0YPCM0UswB1I4eXkDgVuNBQDTF+Kwo1GssLIzZ8wMVEY7KIhxl64MrEQHRBA39fnLo6jzYDOEaD/bU/14sWRP3mogB8R4iLmym/PjanVYRyJ2SQmFtnl/Hp7MnmTMT8itpwN3N/zNLN9eADOs2RnISRin0QB7iHNCMFdL5FQSDMnJM1jsjXTqKA0nTxMIAf8dHH6TjOy3iJNM4Cn6rxAW3flZAkKynba2gquc/L8YNriD/eorROAjju5V1MAS5+D0K1C+uBibVA4t02srTmQWtpkgR30hQfHe3evDQtvM9NZM/3pDLS8UOXXesOMQHglkY10oQ2qSLZSXJZpAx9F0LqgQ9RNpiggh5m2ggk91IvdP+qCizxtRRJPZxbmhprcZM2P5KQb4YH5GJo2v8Ngb7SB0ZkE3XhaI5EKFJ+J0AaKhlabs1N9xVJkIyF7qlNt1RZHzjq1TjxU3dzNpbZxaqIvSMF7bzVibS8uNaJNXuQmgHWhr2XROOBJ8TwhzxVzQoBkgiDNvUxfwE5wo+je08oUX7kNhffPsBCrjbLaAL1AIxrnzSa8cDpHxxjLdhJtbk3xtJVsgZcqDzLw/kR9M6QYTc9cVI1Uzn3gk7M2DPGZVuWgr49OZ0NUtvtwC8ELWTHwErktTdxi0ucwCp/VB1UNAeWWErLIk+poTQfA1TYycghAMVLgZd6DVvZ8F38JAeoYuzYAlTYA8+CGGXzKUjPO0RVizEm6gow4C0JOlAPWBp6eyewGoK4BWQOy2jekE9P7Q2u5pFmST197KwCou4WXO9tVAlYptHzvEMrs0+4CFWvJ1eEGZTiymGzz3H4pAIXoPYDUEz/czcDUrG0QSYczfSQ7AdKTa8No+qzXWNvXZ8PQDnJlFLomraPfrSCltokNo2grAgr3mIBYEzMCpcpKKSCpUZqLj6raNcFsjKKVnjb3dzLp3rSEIOuh2ghBJ66Pukkczh3G0+P9dI3PjiNfWU8/iOQXRUqQwFVZfW+g6KiFQZwqDg2aSEoLoE0gPH8lHzI2kVDE7Sj7UAxcnsu2JmHutdU4BKWj+ON7pU2GdUopOm5QbIDbay2qYNIn2tlIUvvQp+BUjV/D6Qk/+oAaGfqexCmZMUANo4YOnKYGsYFKZxdwjcX70Mwh2yEezYLME96rLyVDnx54U48+xgpbhAbQ9ntX+OTFFJw+djLnQqbg9LHTFcU1IdVDsAaaxLGWCTR93MiuOX3kVDbhDcAlIHSjQMswqYmaTt4RKYimj1uqszRSnWWR+lGmcApVAFkjZ5oKRSNXueQqQ4i6AlCSSFVX0J/grIl+Zh+hryOMwHC6qHW3W+gFLoJGDUjFtIcm+2HAwEuVW3yyAcRPN2faessakWQBUESrt5MoVgiye0HYMdL6Pt6po4e9W5TrT2YWZ4MM1YJMbJlSk2ips1a6ZIsNGHVJXURXF+69UGBZTpNY0UMLmsQKDQw0yazmlIWaMU3CJfcaaJR+RBG2L7LxTpPsOsPHzILF1s01CRXa4awg02sKFU6Mp0vwnN1vS3AAPH8X8R+IlZJb3uhWd/u8IYseca1uf2bRgpO/mqSWvdHMYoVmvTTJlMxEolF61SHMLFs85ZMmwULDcAWZgy2VAbkkFx107CgFfiNfKv3ERNs4LtF2gtRLbXzZLv+pEFnpdTa+IenU2r59QG2oTa+QRPWN/MC71JOA1Ds7eoBJ4rnEF/8dvRJEbu7Db6/ef3v1Q5xEv0Mne39zQz787inww/Q9/fTHb9++vTpmWfzesh4fH09Szwe79ATRRQNm60vx0AnES0D4ye/oxmHyWpbkxYeeS/7OnZNC7kkKszw+qXS+JX/u0Ig5O6YwxLY6bDcnB8chr8du0ML707dvybdv4Xff/UC2/ZG72L6LcS+SFIJP/gf+16LP/WB1NPwTsRplimyAcf/z+/+oPrp+IpsJU/TVv2FjJTBA9nPRn3vgp7B+95YM1avnVmFUNMACuY9Niq/USl+2Vb+9Kq8wPUl9h6ygQevESZxy9Ip+XZFD5075/rJW//dX379yotiD7s+eD9NX71/9GyoHZEZ8c0zL5BTtCyJLbEevm9ll+BeLtCrFRzm9c6b4hgiNEu/goai4epl8Sg8qoQ823xO8DFVw9Nfrzfn52enZ23cXb4lXNNlg0mwyPycQfr37fHvVnLAQFf7mzenF+Zmw7JTeH448L8nsDKSdOSIxGkj+5s3Fxak4iZ2fwyyKsqOK+NdvL7dv3rx7J0wAxHF5bauC+A0q/u3lxdmlRCE4ZEdsGWxEqeP5qBeNEhU+5+/ONhfnF+dbVToZclClctlsN++2l5cXF+fiVNr3+6kUzztUQ95uT99J2KN1a58Kibdvzt9tLlAlEeSAU0DbtOtTK4rLizdv3l5sLzeCDFr7YeQLAbUOp+fbszOlMijvs1Ri8uYMtZmXp2dvFKmocLh8e/729N3pGwkOu4zEyGrOgBzhfHPxdqssv84ZKVwKZ6fn2CckGBxArFQZUa/59vL0/PLN5p2M/k6W+CriL07fvsN3REp0F1R46hwhDpISfDQtIuMwJXOco0b68lKibra67xCSqwEUPfMM9Rfn5xcynlmRAS4SkHmpWsfx7u12u0FdmExYk9nHCB9YdkFcTAAqhVdn2/Ozd+cbiboydl+uCqXLzeWbt2dvzyVsQ3dVyvvIGxRsnm0vhHsyPJvkQxjj4xdqAdbp2ebsHDWhEkE3XQxXqiMo0nx3/ubsrYTxS/l0KkWlD0Ot2Pbt+fmpDIsiYZWG4A7VzneIwzuJhrxDIoEH5cbr9N3bt29R564UadKblpUajC2K89CgiJtHORvx4ZfrX+9uX99++vCXk8CVaTPfbE8vz9FoWFRys/2m03/CXQfqO96dCcSYg7Il47l3by/Ozs65e61S9Ne7a/uqnC5M5cKJs805iif4e8yG2vABZ1UnKwnVRg1Bs2/P3m3evTuXKXGv0xza9Cs5IhdvTi9Q/ZMwQ48HSTlPzp4oMdq8fXex2bx7yx/pNTmRgZe6XdAIfHu+3b49426nuyTqjB/qhbQ5275F/vLmnHsgXLLxvfAeJnvPhye+TMv09g0ag59eivsp1hV9F+OIEs/eyvQLqGF6g5vGnmzWfKUXoE7JwlvtyOHTw+lJHB5kZF++Od/gZrEfq/CK3siKPrtEDdPm9LRfI3lFbyVFX1yi0fUbpLa05DNpe59doNDw4q28vc8lRV9ebC7Pz98ODFdYkkEcS3a177aX71D4945fSyxLqvlCYczZ2bs3A20oS1RhSrn4ZXN6cXr27vRSQLMiZpIT9+bifPvu9LQfsYyY0d4nEOIpGKmy25ydnaLI/eKSX0HBZVhxSnj2YYOG/PzVFa9dSMp6e7F9d3kp3P0QC7g7ufpysX1zjhpi4dCkFCrZ1W7eXVxskINJjJPxuj9EPX+WKY6J3ry7PMerETJBeTs6lSru88vTt+dnF/wjoZ4NfOiS/1wvvfpVacC8fXP6bnPx7p2w77XJeCSLhAPl6v/rd6h9227O+JdkpljIBeuoyp++uZQZt3fKRa1QUGz29s3lGTKIxIRju5bssnCjOCu92Z5hZ70ULZqxTQTiccT55eXbzflABCNukFMlg2zRgO4cr61KDF3qjUe2AzLgR5JzwJcXl9vLjRSDtjUUq+323Ra1opcDwbQ8Ebl47AIFmqfvtm/IbozbjzdfPn28+nj3V/v27refPn62v3z9/OX6693H69tX71/hXTKdHSNExH/gvR8peIDubRY59/+Mb97CC3v44/f4H/wA/r9XMUiyz3FY/vm+/AXuk7MtxgOnm9P9xWbrBWfb8svvy1+KzSK37v2nyCGRSg+HtcOt/P4/i3+wSX4qlmFfqAL/iUoLlc3/vr66s28///b1ihTQD39+CvzvaGH/+O3V5uT026vvYOhE+IwX+uC3u59fv/326s9/+pZ8C8sdSN/R8fDzLeIHf6ycD2/7Scimn33kuzD5LgQB/pr6YvV174G6AWs8g59Cw/3qmW7L9l2eeOhz/Mx76+q99RsKUFPrwQuPD9ZtZZXbLHe9yHq4tB+j5D6NgQOtrk9aPA2pVZO3CvYNbRo8G5GiAYYNdGtc/tGo/CNTfncO2QCJrggGk+6csgEmXRE8TMwUTFcEg0l/wtkAl74Qtl0G+2kz9hkUxWbWmxw3w6onhpeRMY/uiWEyGpvBN8JtTCA/y8H5/Xn4DooeYT68CmCI67CwCXbs5QGDLNlC2bVnJB43U49GBIqzNNb+jAicZNmbjzBKsSdNkJ9pE/akMfh1lrIMcOpIYEWKnZUtE+FiR0TJpBNCd4YDRa1mDxfKzfqsocLI/n6NOjq8Zwp4Rw6D29H1Ex4UwxG4GiXFEDQSN07vnDfCkkMuL+nO/voZ6HYkMoj2D6bop9aXwdsldqYVjVhtVKIA0c3sRDciRAfn0E3yHBTITbO7BDMH065MNln2eSojPNni2BRZZ2qMEGQJY9NjnbYxQo8ljEGPcRBHPzWGIAatwdM5+kkNiuEqyIEjO6aLc0DkSK1lbUU2U2lZ0jhtOacRuWLD3mEkM5FhTwwvJXo+aQZWVNIIsc6xJTOcOkLG7NQ5x2TIRh0pk4RGzzaZ5DgqmHN41D8CZX6k1JfJ3dr1zjzM0ej1hPLYdvBEl2HbDsocbXjYZ75MNUBsiVw9ytiZMNM9zJhsHvL9czKGGfcFjq1qJeaH9m0ZvMPSWUekXPSGDuWZ4TYkaaS17B3WM9M+9sRMU+qd3zPKrCeNbxqX7GxvzeI2lOmdbdCoAeP0BMOsvaMOBplsOJlsjTPZcjI5M87kjJPJuXEm520m497N3HjFXLYoqlHaWbdoPVLmUGs903vqJwLUeab31K2H6EXhJ7BLe4/2Hr7++evZ9uYXvD+v92gfmWSyGnyy22ThCao8tqvdblOLhDRvFWp9Mouspfl+ilskEFqxRUx+dvHmzTl4c7F9u33noA+pVev0c4V1rIb6VqWdVVC3BnlZHPo8pxkM1qfOAK0hbXrrT8wi/lhcPMtTxoM7Gaf6JNOGofwtJjmOwq7etYETxKvTqGIlpsr0QvgCmnTXyzkU2eV7Z32alKwEVUlAsEZdKC1RZbJVFgylJaSME+TrU4WSElIEywz30fqUaRATUygA6N3USbw4iya3Zy6gV4+fmHpxcUPtypSirIRUgWusQ1CiDu3TxFlhDapoCSlziJ1khc10RUtQGW+FBVOyElbFjqMkW6c+FTUhpY77VdacipagMk+r1OVJXBVvu8ImgJISUwS4a9SEshJTxQHOEa5QmYqXkDo+CoTWp0zJSliVpx1YYbDZZCalUvP+snWq1mQopiIkKz4r1KwmJqbQOjtTX6oz9VfZmfoynan/cHBXqAplJaRKkK6wN6WkhBSJkxU2aZSUqCLFzUv+OhVqkhNSLMmcFfpayUpIlRQ27rVblz4tamJKrXH2JpWYvUmfU2c/uVdiAV0qXkLqrDSokQtp8pXGNLlcUJOnYI3zNxUtIWUe3emcDPPrUrLiUSWgG5hWo0WTkMymg5XoMcRLaNcB44vBjwc+7J+m7R+vHdxdgzOBBFFogzge3Y2Dvh/fiFPgTG3EwbtHp3fg1MdyGVtwGh5RP6vfF4aMhM8MW8XfFtamcYbYanMZLP/OJsY1se/R6SuwsJeqbxfj81IvdAadtFN2WRR4BgL2jtJ1S0T/pld11+IHyqm7Id8z718snlT2NEkncqHt+Mj/vL3nVLfLL0KawWVSCW9NWjDJTJcFDHMDu3A4jV8Kn6Y5U9PJrIJjTWXPu/GbCzp0KZ6LauxxJPoySbYiME0XOXq6nA9U0jmIZiDLDcxZ8TKtxHepsrr1zi7vhKtXLOqE9s3AU0rSS9Jr8Rzl8Zw6WPBiZJsEeP18Ma6ldC7n0RH8FQd44yTKIifyR2O/oWe4orrBk8n6a2hbFav6pQyRSqk923aji0X4eSyCPKXcL9bcw4m4xkoK36Q9EaI7UZLBp9fB2dn0cLLQLksA46BG5/EE+hCkXPv9fW/XAEctbL47AYYLh9jPQiayahtYDRYW5W8xyOmYluCtgYyiCwIQdl1AqjBYxUFFLFMW1beURb9AGvQYc14jh1O4z62Q++2NGjmBi1s4GfD3kphB27rDx840WpdOiy5r34JE38I1OYM2Jrl3TZqYCFjYwoRD38AVNYP2lennSt4LW61nryavRefd+1bGeXHqtBTKISoNxuwOrvGYsCOvHRoOsREPFScHBI1cL1PTwf3B6oAd6cS4C3f5oVi70T+86pKm4ym2eEvIvfoeM6GnAUfpali7RlewmG6odo9Xl6GhBNdgQmw4MTCgYKwjDLcAwp0TnazT38Z2SwpJY40n6BOtlrbmpa9bmntJqbaBD0nOINVWJBvIjmSwFaGs62aEId+apO30EmbNS3tQ/jRt9xn97TnkIkZ3twx1Jodp+v7WAfEyrLuip8nG4DFZ3L3ZJDgUgIkXuaikFldilMi0Iulz6CzDvCN5mipwHBgjb/PSbKH2cJDANHH4lMEkBL69i0J859dSrcsoj2k1OonwZiY/IH2UcpU7dAnGDOGThJFM555k6puXa1suhys4dCqhyAM8tyv0pesf3JRVHB+KMrC22lewGt30JHM0jaK5OzUTnsjjyR8pzm7nsdSuYpHivNSZHAQjxXlZd0VLR4rz0maTUIoUZ1ZilIhYpDgv845kqUhx5vZwkIBKpDgv/1Ee02rQRgn1XzPzbgsWD2nnZTsgXTiknY0xQzhnSDu3Fw9JnqTq8+bq18vTH07ezyBpZp/OCL3hHTqDxMgGS+QaO8/3sufZafbFc3QVc5rTE7FnY0y2QLUp5U7SzJ5jEzktxhhWIsUHqjM38H3pk/akF8XPa9GGULGR9BKb7oiDGthwV4Y6JtfHStMzFseIaq21sSYpjnOM+BUqY1VqNDgZ2SeIBZAdAwb8ooS2i/tHfc/M7h5O45ZsuuYdpMjvMY3XkRqoPVi1hjVFQQ1XqpWxetEYiJqpGcUYpjHcNbRXmc/KDSJDzc8gUWPtUXF224zZC+xFvbmg0DVzTcyIXRsztmm+w5dAhweDjj0kblkPH2I06Oqj1A2VDWNfuK6yMLItnNfsnQ3hXVZGLHoEXAcfJA2K0HFH6sF0u5hdEYdBs3a4mbGuYyhaLDRwlgs2kOxhqzrmIg2TvR0hv3CXN9zddZita4t4fzjUn284eSJPmTYpDnyb8kZnGYS2WiIiWRL5PkyUNlyWV5TOsPeiZlzvwGjJnpojqh4m15L7MDNw0pifcYuE5n0Yc87KN5SUnJsv7uFFYnfAuTc9JzpEt0+Ai7Lvhfc+eDaRmIGPcouAGOU5tudM8+bbqlO+FqPSwfVlIdYN8UtM9j4dBm/AEwgSuiFC7T5mg4OGResQAavTjApaZFaV6aozOpPKc+Um3kOnpx10FHwz7XQhD2f+GKg3BM9oigo0vKsSVBRKWoXUqserOPDkXyPi4CqI96hwOyVHfz1aXiYT0rDVLhu7ioN4eS1KvEdFrRHpN9GxF+mrmuQCnpn9G8ssvbuUb96pzVyAxKEp9Qv2VUdK7uBD100e9DkEwpvbHwoVSo+gBARq/eKU2zzMuzIWNLMnU4WpL1MCgmW0KOU2D+2BXb++wYTnBmrHj5x7OwAhOAzEZdK1uAVraFKEYX2quNWiUNaUYV4cfuQNvIpnmWdzqjG1xsjx1JHht+3UQNoBPYXWoCes3wp1kvTBtbqftOet1+nG/E137zrQRi1bymX200Fe4vVvfcpw6uGtUJEBTpoD/CKnlv4QgeIS+rNX+bZSZZ3vUuLxbfoOvqxwVUpQQgIqzDoU59KBPThnKoFPqcVHmKAuaFWqtHmZ70Rarjx3Q9WxBG1yu5QEa9eqlBi5m3Ssdq1Kh7G7rxlKGLmMWEWHkYuIpxuIVWnS5iWlkKmzNHrUYh27EWn9ULUTaf3Q40uMJzoGQSysIU4KZijughIxRaMc8FiGZPXDS4+LG4dea8XHVHNo64UZTJI8zvijW3b/29461VsIHSwfJ0i91A6R3vaDl2T5Ao1SzwakAgOcZ3+QnNAWtb479sStRGEWNflKyjkO8lZpknJih9MmHOVsF3shg9kbHJZy4xQ1tzQBDKLkWf8guo07u23b4kvD9knxeEz7rSpBTQKxMEP5tzSoxyLKNZ/UgaJ5TFeh5gg5idJMYAaSA5x/FYirCJvsJMpt9vaaq8B4W+qOLeIo8lfliBMEJVVcr27SNeyw2iay5mZ+4mtdVZOGllpqJrXiGjVqcJPp91D7C8MyjR7eIrsOJfl4yrt0nERYu6FwkDsgZBu3RCeHNs3eJcdh0ZJNt7PqsxQeYHI1E9N2WtrnKgt1nK/Jz9j5sP6AJc41jlLifIl5OCS26pAqBjP0QHE+vy8hVcuWuRCveQAbR4+okmoYv3aOfI9eV9G2a4vCUiFqiwTxrvL6FDZBjhwjvbdhcL5i3Sg7LsW8QbugZs1Dg2UDGbXklZxmqtY3pT6Ese1HUSzj8Stwh1qBnkvI+nlxBc+qVas5yii40J42MQ3Ht1NOVun11OWWkiM0jaQw4A0Q2hVnWaPRoKFHiWd8OlRL1qfN8C1ffJ69CnUGOGkO7nDUCDylA5ftw7dZNLw43bE3Frrc1DDVmrQbmLHVo6O41knwFjn70FStS4Rr5gm/cA+TEM4/UTrEvabCN73UeGfuGtym3+PCbX1yzKGYAlhFEXT48JdD88VVFEaH0AwTAlX1W0r/cmqgSUS0HVgDd8V6tAYVZL2PtydH8W/mBTr3GNSYCzREpejqqGuLDNcB0OoNMsxJMsdZlR4tVhIKxUmE3l6fSjUvCaV2+Sp1qmhJqLS+GtSmxdWjt19eoEHtaDPEyHyH3miEFrRAebC8RUawFJfn32WjuUPMXeiDZ32dYYE3ezUuxJZVuCbB0w4VT9sgCR4uA/uAOprbFbDv8DFfaanR5nZ4qjutrDUJ8xkgYDCUmIV3BU7GytCJ3PlmgYl+5eoNtm8lXnMbEj4EHBeLcFkIQ+FkfyD35xsNFobCoomZuhwm2xD8wpJkuUnaBxjCxJvvjNqQZRsc+Eg7wDnOXWvalCsGfITnjPyG6PLmlygftvc+SI9LU65Z8BGf9eTuEGfuc7rk6Wj3O3SWbdNqCnyUY3BYtt6VBPjoZglwluVbMeAjnGeeP99x1CHCFQPDx7iaXWq5bQQncp1xwN9QH8fZ44z4uvwFqXOTpH3XklauGIh2SEuSbrEQ6JCW5MydlqXZGyxJuKYg0CEtSbgkINK+L8m3YiDfvhfp+TmbeFMXCUyrXEi2OizmmETwvd3UJMJwH9meGghmntMnxImnNEUPGKzD0gnyZThSwdMM4VIMIS/DWTNJtSiOpHPucAzShXyRCp5mGCdzNq4NhlTwNMNZ11JbFNnrpV2O9HKlRVjWsqd5zrs82KLJXALkzaLC3/rP13Ni/cikcEM0X+u/CEcqmIuhXdxTvxjRhvwJvnh5bzGrtoVPWxakiM9CVq1lT/Pc5XNOqrTqEWsupeujxdGnZfyzks3Rf4Fgn4cLtUoN4dNMHxCbOQ9/t5g2hPOUfTLnJGWr5BPW6t8AxwXWijpcx1eKhqL+RahC3vZz1gyXLYojV5sMRP2LUKSCuRgu2r+35fONUhYhSgVzjlKWaeKpZK5RirOfc2KpwbKWzT2aWoonlc3Lc9k2vs+BdxS4CF3mDjzpuUPG3qLuDGOShJGN/o3wiWt3MK2p1GakLu5sZqVbknoECksP0dJ9CmB6PhZfgYBjkLmzMpaH7eklGx0KxiYgqKy5XaC8bIIRmUrXrDpH7lTt4rNNsbd9vhpS8y9N1GAwOadAHp412hzmyxl20qdn7uKHKXP39fXzc/b3TNJ8HX/r+dk7/zHyY1GAzja9csu52vOG0rRNb1IQqhnLUq5JCNWMxUkzFhiMXQhdZAUfCO2k7oPmCxE54xnCLEq3xnJDNXVnhjQDLIyGNV152pu7Ua3LCGeAxbwuOeaLV1HSvQiz88TH0PFzd+i2zIa1K0PEnpF8gQTfwmQtysfqi+xZtc/Q2GQxk+DIDHGLX/YH3ryCon0Dk1sD5NriOCx3MDFTxLTaYXh2qM2LjJCCMwMHMIZ4NaWN8sIJFfEJrrez8GpJs4QbkF51/3r3+XarrUVAzZ4pKxCiHbeh4kaLJ0rtzDNxfmCIVkPYZNn07Hwb5cngNcVtbXCk45nYf9pUqOBitcWJu9tUf7VPIOylSOo8U2S6GHdRj8dFQRYFJgZBpRJWwdSiZKxa3ni7lkR55oUGZmRYxJoSR6m5ME6gAzLo4g30OF8H6toMzI2wiLLlj9KGDzDM7APSMp6RbFfqKMWfEQiuafPRa0ocpeZ7qYGYhEWrlDbexcI0BQdo7/L93kS4ySLXlzsZCcRJlEWGbp9j0uzJnaSJx/hIoB3mwQ6aWLcc4zogfJLwYwLieHamTamjFOMoycDOn7ERb0ocp5ZEv6PWc0bLNSWOUvtbDvMZTVaJGyWVwiA+ztjI1PLGaWWAXG6NOu8Zi7IrdZTiLX74ZmaGHaETNkwgCGbvRnpix2cGQGpgtMLiVkobp4QXxGcs01qe+CiqbBenZlJvYHADwqHjTi3VjxDEtoEDoF3VS9oW5WXVguXmTH+5uprePvDh6419dXN2Zv9696886WzDKLRT6OS9ScRB22GdZrQc0thqKmTVbK2SCkdSb4KXGljPkCZO2XBwb8Ys9sPWXo8eDGac5UE6IPPtD3eJVHwE/Gk97CkbEdubWlFRK4GxHe7MdlJxR9Gt53tIpU9Iz+n2lW7omd6ihafYTF9ywbR1QyWLMraGCRk5ZTs0F2Zc+aYki02oNaljnFRX2ggxMm9inFApZYRIMagyzqQSM0KlHWcbp9QTN0INh9kzOFAlZoxKEVyb51LJaZKZXpHqr2FLrZTUK0TmNC1WTOhaSUug+LiFa5WtlGxmoa2jV7mo1RU6OlSsHg7IDa6zc6zE6l+s2vk5zKIoO9o+tAPPdX34CDojIZ5NPZ1nDiDLbJoj03Yh+eGFeGcJuUHbjh5gknhTnpH6Ni+Q/kJhWKbcGcNLzBJUQn8RkwDTy57tYAfdzB9dl+Tb1lUiTm7sIjc5x1GIIgCOHL1+ydBO8xgHcnx3DDITvPS8yasEAMeBPkyK69y1u07X4s20scU3VtM0Vl/zMiHMGGeOoU7z9SgIvRjfYh8aWAkzo3GHMqfCcQpeVPkO8RUa+nFuqBwwVklLfzihwUTl9TQ1RS4HIPZ0kuc4M7BNWp9abZYCrr161bo01XyZ+8bnylHWWN3LK2JqihwlDiBq9E0kktakUIMfhzaOE6xamwY/Hm0C4KxbnQZBntYF0imxYK3xAalCXZY8mh3BZtUl1STIp8/24nLtGjUo8ul0sdmuXacGRQ6dDitv7w5C7R10fo/BPVy1Rh2OHFplxwQC1wsPq9arx1I4Dl6rZj2W/Jo9AD83sR9Rr2Y1S/EIf72qdWnqWKgcmg7CUtzEexi87lB+1FvQz5LQwKFUCRvXWrYGUCU/AccpUAzdSaxPsw5NcQVNHQDVriL7jChDSRTg0sN2tgtjGLowdDy4jvmZAVVH6PK35F6W2mYuJNChZI8if0lSJ9jlnp+R222f11yQDLbC6qIXm4O01Svc5yulMuqIvIdi/vZFqNzmK6wyQBHp+hUtWQqrFwADma91a0dJCiuXeocQZHliYIeLbhVbVIUVdUhOjfVrWfPkVzFLQJjGIMGbq16KuqOclVQ/Grlwx6Tix5HLebjVXnkrPMJYSe11t85swnJKv5joYpw0v/JRDP6Wv5CueJCrsKovpoiZfGVLd/V9FouurMIrb7KHyZpbwm/vPksB48GOZb0wg0kIfNTk5CnOpJBmUWLkuk81w+LpUvSnNcZ32JEGXOmlKT3FmUtxkkl3rRpW5BiNAbuGcM1vrlBrJlHF+c2VqjpCV3zWeg/JSHa1yjKoyk0NrVTHPkvZSYXVK1jzVJ3PXL2qfb6qs9YvQmXxrVC96cPV60lJCkfb+O4lQ4m9tKk4RFVYUUNpmXQryczixFawOZ3wEoqTyVdO5bUX7CBXQztBPLrZROs2EIppmzhNKW7lUsUq0XST3Exb6L0VbT2q7FG6nOAmMa9hwfWqYw+fPtVUbYoEek7km6g+XhfdToDrRWAtu1Xa5OrdOSOkOR2rfGV12xwYKjP48o5g26hrqEy8hSvQWAzZaM2aMvgaSxlj4iCynfZTHnDlQO48NHSuuVfIYI5gimpU5XwryxlwZDAFiQcWZEilj1LceYcwN5D0iZdkLX+cph8597PN0zDJdliMU8493yU5ARYk3OIwnt4b/fD9Jf21yWCcqrOgw1Lh4wSPAP1ve7ogywYDDqpx5D8vTbbkMEEX4hpITtovSbjNYpzywo0WZ3PlzDJ3yCTJmBTs3KyCDW4D9/c8zWwfHoDzPFsIy2Q+TkpcoX0SBXh+ZmUqNWkJKIUnmsirBcxalBqgJahUmuMUoTBboWID1ASUS1MD6bDklKFUBMg/XZy+Wwv7kgsP/TXUd57KDR13SaaV+AmS5NDwkjQrAhNE4yVJxpMED0tG2geOSLuEWDoi7PMYpz3Dbgom1cE9Eh16F0vyu5gkWF25ipN3Lke1R4OPdJ55C3axPRoTF8b4z5uz0wX9oclg4gIZvFsEksRr6YIzg30eo7QTL4aBu7lccLagRWH8ZpIj2CzHs5Q+RXF7cbkoSSp/iqaBG0IFSE7fGFrkx1mUJJU/Psuehgv6ZCl9kuIjQluwr2pRGJ+4Bim8PF9w0rqSPzFyCmKQvd6ePC05cmpymBroIcl4Y82iIUuPxjjpLLHdZLfkVGuDwShVF+7yBXlW4idILhiXuBwrlu5xwQEfFT41AXFcdP7hOE0xzJIoXnBGsEFgnOg8B3GYNFlHbVokj/fufjmOpfRxijgv57LNZIvCKFk/WLAJosLHJx9gECXP9LoSG8mOFlyXYpAZVSCEGYJz7mG2oKU7JMYJe2lm3z8uSLYmMEo08hacN6PCx6cg4ILdJxU+TvB+QX73HPScdMkRZy1/kuaSM2Kl+EmSb5Yl+YZ7TnT56dBpqilYeua2wWB8SnHJNbqEY4Vu0TVmnlXlFG/aBc5xwZF6i8I0WbLLJ829bMkh5hCTaepRdO8tbeiKwyRdfOMknGEn+RjdmsMo3SrL9HJsWxTGyXrBskwr+aM0afKA5Xg2CIwSXXYrDNfmF/yQ7SQL9gVNBjxUF6z3TQYcVNMFZ3aaDNpUeW6YHEoZ1J6VXmjLJ84Pw7uzsziJRneCgRz9DkN8ifECA9iaNouPgCp0r9i8mV6mNWLQElcMJ2GIgZfMdVabW7U+MXHl0ucwCp+XmABkqtWktNrjNJi9yFGaQtEy7TY5/JcuE5g37D5MR0SROEEhUuY9rESRNh0RReZOhsOhzHS+myGFivXnRRWoKfARXmafZosw37Gd4umZ07eN8J7MzzZKP8zgU5aupS0apyWj2Iqq9DQ1GQVX0viO0+JRDL2WLDA92dChYsBDd6njPQ2+vMd4iqeXm1JvUOaeVS9zppTZwRZl3WLBRdv7Y+H6WDHgopslubNsuFBT4CG8/CBMaLQ11wV2I3xZt9PxJPvozcT43i4ByXMvVQdzW6PxlDml5pSZ1RNvsalWbdLsLJuSOQgWi3yLsazEj1EtlyLnZ9mQPEKwXneYnWFL9AhF4HuHcJ6sRF2KLdEjFIut2FXK7/mJDhAYo0uSyaDgNJlxObGi2hY+TXNBq/YJTNMNohnnrjtMqWwuknYCZtzK1idayucmi8rhAaQo7FyadYvIGP1GGqQlvZhFY4x6aAf5ElwruSPkaFqZZWbKqohqmMQY7bIElvLiAQLTdB8TMOPh+w7VUvgYzZlnHOuIenh+kR3121jMEkSHOPCTXqzdYvMYI5/NODVSMc2GlvCbtMixpwVt2Zc/QhY6cX17DfAXiLuHGEwSXqpZ7UofI1qcOLLjyF/ACbrSR4j6QTTnqYySYSV2hFrgzpsFqORWyx0nt0yH2RA8Ri9OZ1+iqxi2ZE+QnPnIXZMj47hdjyKevJhzHr7JsZY9QTJLgLNAk9gSPTY9Blw8OJmfYEPwGL37BbvsjvBxmss0Og3Bo/RmTulQ02Mkchicol2yqIcojFBO0PMoKrKP0McZDOcnPEBggu5yxu1KHyHaPZaxIOtRKlMq+N4is+Vt2RMkixHJYh48SGGCcuClMx6xbjItJU8QRG9vzhYcCQ1z4CJ9D58X8oK2/BGyZLf+ci1CT/xEn1ZOTRYVcpH1xx4FvjWp5Sf6eywm50kXWNJn3MfNnMRdiGElnMtfl3RUbpIz3WQ+UqWGbydntgELueggBT7KdP8k9h3cO9sh3hIFMs9ZVItRVnyKpX6UzXp71og6A1w4laBXmS9KvubARxoncl6SMJXPR3a/d4+Lsi0J8NE9gnRZuiUBPrr4Fo0l2VL5fGRJivQl2ZYE+OjivBZLsqXyORuyhdswAbvOc7f8VMzBP+6Y+TofdszBT3mR/XADBPjpLraaw+YhFd8tqsAAF9UgdUXqtFnxh0pLqjB458ZoqLQk25KAQKi0JN2SAB/d5eZiGCQ4aS+xfaEvnz8cXZLs4KVyo+HokmyHrwxihqMgdKNgob13bB78sfSipCc3vLSD2SW5pgJO0Z34WJR3n4vYJMyi5GsOTdLC92MnwPPtoWN0neeKMHPsoF3q2xhMv1WaFOnuX6shbGyVq3jKDvYGDhuP0CoFclADKSKRFXufUCxvJP/+GNNh+RzEDZ18HePKOOo6SG8PQZYnczNsSh3blzFbPeGoJPPWEM7qsWjdkKsYc9cK7iqxQH0YrQzTx7rjJMoiJ/J73U3rqZ0Px9PwlbUSPWhY7ZKwhURZHbHjiZAX4Mcmx5P80IMQvj3dbi7O+YxfPz+XjrVEa5jEdIksSnqSMU8xPQa7POUrIfLoXHoSYVZP9HSRLMByjCJPGfzxCB44myjy6FzaEWFWT/R0GSzAcowiTxmkngsfgX/PVwzl03PpWMqzhghMl8didCe4SuVycY5ePN7hw31yth0oyP5DT4ftU+9BRpljuXYaQ8fbm1g/aIdHSJZFGFoVT4tJpOsAQy6wOHs+6sNVVcZNcGrgA+zPRPTzAiFeCfQhSCfa4PLhUqeNfXCc8tUTYNSkVBurQ9ia5KShwsV+fvAmDFn6JjkkUWTS9FDoaMcTGbDZ75luq4hSFlv+yFeSPUwTLwY4JQHNgM8Zfw28qH9vxKSR2gTGvuvvnJhQLMN5vFeoU81LSJ2mKeZ3ZoFymoohevaYYfJCppgYcxwSdbMocd4QYsMbQpTw7i6w4+gRKQKzzAsPdgDiGP8kcu1T9P0y5i30rnrtTe8BTuYTEYkg6ublGmRjxiLbl2uRrRmL4AApiFzkgsjmL9k+DEUMWuvvw1Rm7fR34lNjHjXYT/JFbEsahU1JNQzA9qTr/jgnl5eJhOm9l5cIa3skpr4XjHH77y/gCeJKavCNzBNxhsxbovQzr/eBYPmiFxYo0CHe6kWW7FHrkB0Fio2+sUDRUcmDH4oVYfnS/MU4qoPUTPDUFqVqV1QKy/o+tlOpzBI9MbFFQafGgmkxRxSFMOz3EwOogwxZTyfO4GP9gq9xDZ6aqYVUmbarL62mHazGk0gHq0ewH6yNK2U6U7cezRhZvTnUM34MWJOCrLPCHCrSFHfr17FBVFhJw4ctNWk4fCKTQ73OPUCrV7TPV0rlIwhd32wifo0KN9kKq5t6h5Bsylq/ri2qwoqCLIPk7NVL8OMOWS5lvSZAgAKxXfS0Tk1ZTIfUZMxVFPq3t6GFErGTuQ37UvZBOlg9gsKu7sK9Fxq91EePck2iwkqavmdJk4rMy5gmFSSx5er1K1mKN1Hm9h/r0JFJVbgcq+TZhvOqaSrQHl3xkp0hMZuukmUnceMoWXrvhOlbLzQVbJetuLovRVEFFU1nytClIiOdBoeK5Wh39To2iMoNy1ev4fDpfw71Zrs5WJOi09cJc6lcDXRfhMJNtgrD8tXr2qKqNCxfvaodsvLD8lVqymIqNCxnf9FdRfHsGBGzoxR0T/UNv8C7NNLAtZ0g9VI7yaJ0u46pkCa7ajaEyXemCZEGg3V4ZstKpXO2OHJWvWHLvgAdu3x11EHpExedD7p/No0O4snEnrfYgp6DLHKb5a4XWQ+X9mOU3KcxcKC1S9BY+5jCEJsSb4CiiBZL2kRhSkg7MqThm14CeBK4WiU2UAelfvjl+te7W91SG6gsy9r7BELsgPoLtAU9KB/VlQPqbVGFSh48B6LokfzwQlylSAdsRw8wSTx3cuFCkJ6g5EH2qPOcXGQQpFVCVvKKUW6eEEql4J/gHuR+hiSjFgz6rU92EUjcK3q6xfOR4B9JEhfa3J2Q709C1Dy9Pz1B/49eiUGSdd8InPwEJMEJ2aJ4grkVv+LfwOnmdH+x2XoBPpX3XRZFvnNExEekpunJPkHkseoncRL9Dp3shCRfDKM79P4Vfr8ilLr3Y1ju/Qlqrh30r4d+f7893V6cbLYnZyf25mxz9ubN28vNm4vLs3dv3/z/vV1RDoIwDL2LB2CKGn8IZ/AGjcICSzYkDpQf7263dQMTNYqZf3ShvLVr1tcx2HY33cqf8cGeSl/u0em586wJBCUKEKkOKwoZe7jxrXqpDuX58p2qDjEB2H8I/R/POTeeGVMLVwhBSJZNuMukiI9mMhah/cE2mx9TV2pgMibfkhitA1IcrVe5AomQ0dxqcIyFHieOPS0W4GbVKNANrFAltOdY/nuJB7zp1X9Re40zWXxEepHr/RonXp7jOQt/RLQpgH5aqlmNwvWA0K6B4WzoEWlijI9HY6jMN8QfYQmF7JtIFQhVLZO2qWZprmZrprM117M1Nx9rBur349jJnmOC72qQHOqT7pDY2e28xy4Z8PLV00uuCwxgw1ryjE0lX108MBvbmjFiBlZa3O5b00zR=END_SIMPLICITY_STUDIO_METADATA